// Code generated by ent, DO NOT EDIT.

package notificationtemplate

import (
	"autoSSL/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldName, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldType, v))
}

// SubjectTemplate applies equality check predicate on the "subject_template" field. It's identical to SubjectTemplateEQ.
func SubjectTemplate(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldSubjectTemplate, v))
}

// ContentTemplate applies equality check predicate on the "content_template" field. It's identical to ContentTemplateEQ.
func ContentTemplate(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldContentTemplate, v))
}

// Format applies equality check predicate on the "format" field. It's identical to FormatEQ.
func Format(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldFormat, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldUserID, v))
}

// IsSystemDefault applies equality check predicate on the "is_system_default" field. It's identical to IsSystemDefaultEQ.
func IsSystemDefault(v bool) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldIsSystemDefault, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContainsFold(FieldType, v))
}

// SubjectTemplateEQ applies the EQ predicate on the "subject_template" field.
func SubjectTemplateEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldSubjectTemplate, v))
}

// SubjectTemplateNEQ applies the NEQ predicate on the "subject_template" field.
func SubjectTemplateNEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldSubjectTemplate, v))
}

// SubjectTemplateIn applies the In predicate on the "subject_template" field.
func SubjectTemplateIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldSubjectTemplate, vs...))
}

// SubjectTemplateNotIn applies the NotIn predicate on the "subject_template" field.
func SubjectTemplateNotIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldSubjectTemplate, vs...))
}

// SubjectTemplateGT applies the GT predicate on the "subject_template" field.
func SubjectTemplateGT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldSubjectTemplate, v))
}

// SubjectTemplateGTE applies the GTE predicate on the "subject_template" field.
func SubjectTemplateGTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldSubjectTemplate, v))
}

// SubjectTemplateLT applies the LT predicate on the "subject_template" field.
func SubjectTemplateLT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldSubjectTemplate, v))
}

// SubjectTemplateLTE applies the LTE predicate on the "subject_template" field.
func SubjectTemplateLTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldSubjectTemplate, v))
}

// SubjectTemplateContains applies the Contains predicate on the "subject_template" field.
func SubjectTemplateContains(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContains(FieldSubjectTemplate, v))
}

// SubjectTemplateHasPrefix applies the HasPrefix predicate on the "subject_template" field.
func SubjectTemplateHasPrefix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasPrefix(FieldSubjectTemplate, v))
}

// SubjectTemplateHasSuffix applies the HasSuffix predicate on the "subject_template" field.
func SubjectTemplateHasSuffix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasSuffix(FieldSubjectTemplate, v))
}

// SubjectTemplateIsNil applies the IsNil predicate on the "subject_template" field.
func SubjectTemplateIsNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIsNull(FieldSubjectTemplate))
}

// SubjectTemplateNotNil applies the NotNil predicate on the "subject_template" field.
func SubjectTemplateNotNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotNull(FieldSubjectTemplate))
}

// SubjectTemplateEqualFold applies the EqualFold predicate on the "subject_template" field.
func SubjectTemplateEqualFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEqualFold(FieldSubjectTemplate, v))
}

// SubjectTemplateContainsFold applies the ContainsFold predicate on the "subject_template" field.
func SubjectTemplateContainsFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContainsFold(FieldSubjectTemplate, v))
}

// ContentTemplateEQ applies the EQ predicate on the "content_template" field.
func ContentTemplateEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldContentTemplate, v))
}

// ContentTemplateNEQ applies the NEQ predicate on the "content_template" field.
func ContentTemplateNEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldContentTemplate, v))
}

// ContentTemplateIn applies the In predicate on the "content_template" field.
func ContentTemplateIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldContentTemplate, vs...))
}

// ContentTemplateNotIn applies the NotIn predicate on the "content_template" field.
func ContentTemplateNotIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldContentTemplate, vs...))
}

// ContentTemplateGT applies the GT predicate on the "content_template" field.
func ContentTemplateGT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldContentTemplate, v))
}

// ContentTemplateGTE applies the GTE predicate on the "content_template" field.
func ContentTemplateGTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldContentTemplate, v))
}

// ContentTemplateLT applies the LT predicate on the "content_template" field.
func ContentTemplateLT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldContentTemplate, v))
}

// ContentTemplateLTE applies the LTE predicate on the "content_template" field.
func ContentTemplateLTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldContentTemplate, v))
}

// ContentTemplateContains applies the Contains predicate on the "content_template" field.
func ContentTemplateContains(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContains(FieldContentTemplate, v))
}

// ContentTemplateHasPrefix applies the HasPrefix predicate on the "content_template" field.
func ContentTemplateHasPrefix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasPrefix(FieldContentTemplate, v))
}

// ContentTemplateHasSuffix applies the HasSuffix predicate on the "content_template" field.
func ContentTemplateHasSuffix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasSuffix(FieldContentTemplate, v))
}

// ContentTemplateEqualFold applies the EqualFold predicate on the "content_template" field.
func ContentTemplateEqualFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEqualFold(FieldContentTemplate, v))
}

// ContentTemplateContainsFold applies the ContainsFold predicate on the "content_template" field.
func ContentTemplateContainsFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContainsFold(FieldContentTemplate, v))
}

// FormatEQ applies the EQ predicate on the "format" field.
func FormatEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldFormat, v))
}

// FormatNEQ applies the NEQ predicate on the "format" field.
func FormatNEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldFormat, v))
}

// FormatIn applies the In predicate on the "format" field.
func FormatIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldFormat, vs...))
}

// FormatNotIn applies the NotIn predicate on the "format" field.
func FormatNotIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldFormat, vs...))
}

// FormatGT applies the GT predicate on the "format" field.
func FormatGT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldFormat, v))
}

// FormatGTE applies the GTE predicate on the "format" field.
func FormatGTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldFormat, v))
}

// FormatLT applies the LT predicate on the "format" field.
func FormatLT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldFormat, v))
}

// FormatLTE applies the LTE predicate on the "format" field.
func FormatLTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldFormat, v))
}

// FormatContains applies the Contains predicate on the "format" field.
func FormatContains(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContains(FieldFormat, v))
}

// FormatHasPrefix applies the HasPrefix predicate on the "format" field.
func FormatHasPrefix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasPrefix(FieldFormat, v))
}

// FormatHasSuffix applies the HasSuffix predicate on the "format" field.
func FormatHasSuffix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasSuffix(FieldFormat, v))
}

// FormatEqualFold applies the EqualFold predicate on the "format" field.
func FormatEqualFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEqualFold(FieldFormat, v))
}

// FormatContainsFold applies the ContainsFold predicate on the "format" field.
func FormatContainsFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContainsFold(FieldFormat, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotNull(FieldUserID))
}

// IsSystemDefaultEQ applies the EQ predicate on the "is_system_default" field.
func IsSystemDefaultEQ(v bool) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldIsSystemDefault, v))
}

// IsSystemDefaultNEQ applies the NEQ predicate on the "is_system_default" field.
func IsSystemDefaultNEQ(v bool) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldIsSystemDefault, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotificationTemplate) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotificationTemplate) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotificationTemplate) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.NotPredicates(p))
}
