// Code generated by ent, DO NOT EDIT.

package certificate

import (
	"autoSSL/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldID, id))
}

// IssuedBy applies equality check predicate on the "issued_by" field. It's identical to IssuedByEQ.
func IssuedBy(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldIssuedBy, v))
}

// IssuedAt applies equality check predicate on the "issued_at" field. It's identical to IssuedAtEQ.
func IssuedAt(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldIssuedAt, v))
}

// ExpiredAt applies equality check predicate on the "expired_at" field. It's identical to ExpiredAtEQ.
func ExpiredAt(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldExpiredAt, v))
}

// AcmeAccountEmail applies equality check predicate on the "acme_account_email" field. It's identical to AcmeAccountEmailEQ.
func AcmeAccountEmail(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldAcmeAccountEmail, v))
}

// DNSProviderName applies equality check predicate on the "dns_provider_name" field. It's identical to DNSProviderNameEQ.
func DNSProviderName(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldDNSProviderName, v))
}

// RenewalDaysBefore applies equality check predicate on the "renewal_days_before" field. It's identical to RenewalDaysBeforeEQ.
func RenewalDaysBefore(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldRenewalDaysBefore, v))
}

// RenewalEnabled applies equality check predicate on the "renewal_enabled" field. It's identical to RenewalEnabledEQ.
func RenewalEnabled(v bool) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldRenewalEnabled, v))
}

// Certificate applies equality check predicate on the "certificate" field. It's identical to CertificateEQ.
func Certificate(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCertificate, v))
}

// PrivateKey applies equality check predicate on the "private_key" field. It's identical to PrivateKeyEQ.
func PrivateKey(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldPrivateKey, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldErrorMessage, v))
}

// ServerGroupID applies equality check predicate on the "server_group_id" field. It's identical to ServerGroupIDEQ.
func ServerGroupID(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldServerGroupID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldUpdatedAt, v))
}

// IssuedByEQ applies the EQ predicate on the "issued_by" field.
func IssuedByEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldIssuedBy, v))
}

// IssuedByNEQ applies the NEQ predicate on the "issued_by" field.
func IssuedByNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldIssuedBy, v))
}

// IssuedByIn applies the In predicate on the "issued_by" field.
func IssuedByIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldIssuedBy, vs...))
}

// IssuedByNotIn applies the NotIn predicate on the "issued_by" field.
func IssuedByNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldIssuedBy, vs...))
}

// IssuedByGT applies the GT predicate on the "issued_by" field.
func IssuedByGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldIssuedBy, v))
}

// IssuedByGTE applies the GTE predicate on the "issued_by" field.
func IssuedByGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldIssuedBy, v))
}

// IssuedByLT applies the LT predicate on the "issued_by" field.
func IssuedByLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldIssuedBy, v))
}

// IssuedByLTE applies the LTE predicate on the "issued_by" field.
func IssuedByLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldIssuedBy, v))
}

// IssuedByContains applies the Contains predicate on the "issued_by" field.
func IssuedByContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldIssuedBy, v))
}

// IssuedByHasPrefix applies the HasPrefix predicate on the "issued_by" field.
func IssuedByHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldIssuedBy, v))
}

// IssuedByHasSuffix applies the HasSuffix predicate on the "issued_by" field.
func IssuedByHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldIssuedBy, v))
}

// IssuedByEqualFold applies the EqualFold predicate on the "issued_by" field.
func IssuedByEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldIssuedBy, v))
}

// IssuedByContainsFold applies the ContainsFold predicate on the "issued_by" field.
func IssuedByContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldIssuedBy, v))
}

// IssuedAtEQ applies the EQ predicate on the "issued_at" field.
func IssuedAtEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedAtNEQ applies the NEQ predicate on the "issued_at" field.
func IssuedAtNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldIssuedAt, v))
}

// IssuedAtIn applies the In predicate on the "issued_at" field.
func IssuedAtIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldIssuedAt, vs...))
}

// IssuedAtNotIn applies the NotIn predicate on the "issued_at" field.
func IssuedAtNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldIssuedAt, vs...))
}

// IssuedAtGT applies the GT predicate on the "issued_at" field.
func IssuedAtGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldIssuedAt, v))
}

// IssuedAtGTE applies the GTE predicate on the "issued_at" field.
func IssuedAtGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldIssuedAt, v))
}

// IssuedAtLT applies the LT predicate on the "issued_at" field.
func IssuedAtLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldIssuedAt, v))
}

// IssuedAtLTE applies the LTE predicate on the "issued_at" field.
func IssuedAtLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldIssuedAt, v))
}

// IssuedAtIsNil applies the IsNil predicate on the "issued_at" field.
func IssuedAtIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldIssuedAt))
}

// IssuedAtNotNil applies the NotNil predicate on the "issued_at" field.
func IssuedAtNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldIssuedAt))
}

// ExpiredAtEQ applies the EQ predicate on the "expired_at" field.
func ExpiredAtEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldExpiredAt, v))
}

// ExpiredAtNEQ applies the NEQ predicate on the "expired_at" field.
func ExpiredAtNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldExpiredAt, v))
}

// ExpiredAtIn applies the In predicate on the "expired_at" field.
func ExpiredAtIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldExpiredAt, vs...))
}

// ExpiredAtNotIn applies the NotIn predicate on the "expired_at" field.
func ExpiredAtNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldExpiredAt, vs...))
}

// ExpiredAtGT applies the GT predicate on the "expired_at" field.
func ExpiredAtGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldExpiredAt, v))
}

// ExpiredAtGTE applies the GTE predicate on the "expired_at" field.
func ExpiredAtGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldExpiredAt, v))
}

// ExpiredAtLT applies the LT predicate on the "expired_at" field.
func ExpiredAtLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldExpiredAt, v))
}

// ExpiredAtLTE applies the LTE predicate on the "expired_at" field.
func ExpiredAtLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldExpiredAt, v))
}

// ExpiredAtIsNil applies the IsNil predicate on the "expired_at" field.
func ExpiredAtIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldExpiredAt))
}

// ExpiredAtNotNil applies the NotNil predicate on the "expired_at" field.
func ExpiredAtNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldExpiredAt))
}

// AcmeAccountEmailEQ applies the EQ predicate on the "acme_account_email" field.
func AcmeAccountEmailEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldAcmeAccountEmail, v))
}

// AcmeAccountEmailNEQ applies the NEQ predicate on the "acme_account_email" field.
func AcmeAccountEmailNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldAcmeAccountEmail, v))
}

// AcmeAccountEmailIn applies the In predicate on the "acme_account_email" field.
func AcmeAccountEmailIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldAcmeAccountEmail, vs...))
}

// AcmeAccountEmailNotIn applies the NotIn predicate on the "acme_account_email" field.
func AcmeAccountEmailNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldAcmeAccountEmail, vs...))
}

// AcmeAccountEmailGT applies the GT predicate on the "acme_account_email" field.
func AcmeAccountEmailGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldAcmeAccountEmail, v))
}

// AcmeAccountEmailGTE applies the GTE predicate on the "acme_account_email" field.
func AcmeAccountEmailGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldAcmeAccountEmail, v))
}

// AcmeAccountEmailLT applies the LT predicate on the "acme_account_email" field.
func AcmeAccountEmailLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldAcmeAccountEmail, v))
}

// AcmeAccountEmailLTE applies the LTE predicate on the "acme_account_email" field.
func AcmeAccountEmailLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldAcmeAccountEmail, v))
}

// AcmeAccountEmailContains applies the Contains predicate on the "acme_account_email" field.
func AcmeAccountEmailContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldAcmeAccountEmail, v))
}

// AcmeAccountEmailHasPrefix applies the HasPrefix predicate on the "acme_account_email" field.
func AcmeAccountEmailHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldAcmeAccountEmail, v))
}

// AcmeAccountEmailHasSuffix applies the HasSuffix predicate on the "acme_account_email" field.
func AcmeAccountEmailHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldAcmeAccountEmail, v))
}

// AcmeAccountEmailEqualFold applies the EqualFold predicate on the "acme_account_email" field.
func AcmeAccountEmailEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldAcmeAccountEmail, v))
}

// AcmeAccountEmailContainsFold applies the ContainsFold predicate on the "acme_account_email" field.
func AcmeAccountEmailContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldAcmeAccountEmail, v))
}

// DNSProviderNameEQ applies the EQ predicate on the "dns_provider_name" field.
func DNSProviderNameEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldDNSProviderName, v))
}

// DNSProviderNameNEQ applies the NEQ predicate on the "dns_provider_name" field.
func DNSProviderNameNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldDNSProviderName, v))
}

// DNSProviderNameIn applies the In predicate on the "dns_provider_name" field.
func DNSProviderNameIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldDNSProviderName, vs...))
}

// DNSProviderNameNotIn applies the NotIn predicate on the "dns_provider_name" field.
func DNSProviderNameNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldDNSProviderName, vs...))
}

// DNSProviderNameGT applies the GT predicate on the "dns_provider_name" field.
func DNSProviderNameGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldDNSProviderName, v))
}

// DNSProviderNameGTE applies the GTE predicate on the "dns_provider_name" field.
func DNSProviderNameGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldDNSProviderName, v))
}

// DNSProviderNameLT applies the LT predicate on the "dns_provider_name" field.
func DNSProviderNameLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldDNSProviderName, v))
}

// DNSProviderNameLTE applies the LTE predicate on the "dns_provider_name" field.
func DNSProviderNameLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldDNSProviderName, v))
}

// DNSProviderNameContains applies the Contains predicate on the "dns_provider_name" field.
func DNSProviderNameContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldDNSProviderName, v))
}

// DNSProviderNameHasPrefix applies the HasPrefix predicate on the "dns_provider_name" field.
func DNSProviderNameHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldDNSProviderName, v))
}

// DNSProviderNameHasSuffix applies the HasSuffix predicate on the "dns_provider_name" field.
func DNSProviderNameHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldDNSProviderName, v))
}

// DNSProviderNameEqualFold applies the EqualFold predicate on the "dns_provider_name" field.
func DNSProviderNameEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldDNSProviderName, v))
}

// DNSProviderNameContainsFold applies the ContainsFold predicate on the "dns_provider_name" field.
func DNSProviderNameContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldDNSProviderName, v))
}

// RenewalDaysBeforeEQ applies the EQ predicate on the "renewal_days_before" field.
func RenewalDaysBeforeEQ(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldRenewalDaysBefore, v))
}

// RenewalDaysBeforeNEQ applies the NEQ predicate on the "renewal_days_before" field.
func RenewalDaysBeforeNEQ(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldRenewalDaysBefore, v))
}

// RenewalDaysBeforeIn applies the In predicate on the "renewal_days_before" field.
func RenewalDaysBeforeIn(vs ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldRenewalDaysBefore, vs...))
}

// RenewalDaysBeforeNotIn applies the NotIn predicate on the "renewal_days_before" field.
func RenewalDaysBeforeNotIn(vs ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldRenewalDaysBefore, vs...))
}

// RenewalDaysBeforeGT applies the GT predicate on the "renewal_days_before" field.
func RenewalDaysBeforeGT(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldRenewalDaysBefore, v))
}

// RenewalDaysBeforeGTE applies the GTE predicate on the "renewal_days_before" field.
func RenewalDaysBeforeGTE(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldRenewalDaysBefore, v))
}

// RenewalDaysBeforeLT applies the LT predicate on the "renewal_days_before" field.
func RenewalDaysBeforeLT(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldRenewalDaysBefore, v))
}

// RenewalDaysBeforeLTE applies the LTE predicate on the "renewal_days_before" field.
func RenewalDaysBeforeLTE(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldRenewalDaysBefore, v))
}

// RenewalEnabledEQ applies the EQ predicate on the "renewal_enabled" field.
func RenewalEnabledEQ(v bool) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldRenewalEnabled, v))
}

// RenewalEnabledNEQ applies the NEQ predicate on the "renewal_enabled" field.
func RenewalEnabledNEQ(v bool) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldRenewalEnabled, v))
}

// ValidationTypeEQ applies the EQ predicate on the "validation_type" field.
func ValidationTypeEQ(v ValidationType) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldValidationType, v))
}

// ValidationTypeNEQ applies the NEQ predicate on the "validation_type" field.
func ValidationTypeNEQ(v ValidationType) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldValidationType, v))
}

// ValidationTypeIn applies the In predicate on the "validation_type" field.
func ValidationTypeIn(vs ...ValidationType) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldValidationType, vs...))
}

// ValidationTypeNotIn applies the NotIn predicate on the "validation_type" field.
func ValidationTypeNotIn(vs ...ValidationType) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldValidationType, vs...))
}

// CertificateEQ applies the EQ predicate on the "certificate" field.
func CertificateEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCertificate, v))
}

// CertificateNEQ applies the NEQ predicate on the "certificate" field.
func CertificateNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldCertificate, v))
}

// CertificateIn applies the In predicate on the "certificate" field.
func CertificateIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldCertificate, vs...))
}

// CertificateNotIn applies the NotIn predicate on the "certificate" field.
func CertificateNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldCertificate, vs...))
}

// CertificateGT applies the GT predicate on the "certificate" field.
func CertificateGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldCertificate, v))
}

// CertificateGTE applies the GTE predicate on the "certificate" field.
func CertificateGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldCertificate, v))
}

// CertificateLT applies the LT predicate on the "certificate" field.
func CertificateLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldCertificate, v))
}

// CertificateLTE applies the LTE predicate on the "certificate" field.
func CertificateLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldCertificate, v))
}

// CertificateContains applies the Contains predicate on the "certificate" field.
func CertificateContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldCertificate, v))
}

// CertificateHasPrefix applies the HasPrefix predicate on the "certificate" field.
func CertificateHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldCertificate, v))
}

// CertificateHasSuffix applies the HasSuffix predicate on the "certificate" field.
func CertificateHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldCertificate, v))
}

// CertificateEqualFold applies the EqualFold predicate on the "certificate" field.
func CertificateEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldCertificate, v))
}

// CertificateContainsFold applies the ContainsFold predicate on the "certificate" field.
func CertificateContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldCertificate, v))
}

// PrivateKeyEQ applies the EQ predicate on the "private_key" field.
func PrivateKeyEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldPrivateKey, v))
}

// PrivateKeyNEQ applies the NEQ predicate on the "private_key" field.
func PrivateKeyNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldPrivateKey, v))
}

// PrivateKeyIn applies the In predicate on the "private_key" field.
func PrivateKeyIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldPrivateKey, vs...))
}

// PrivateKeyNotIn applies the NotIn predicate on the "private_key" field.
func PrivateKeyNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldPrivateKey, vs...))
}

// PrivateKeyGT applies the GT predicate on the "private_key" field.
func PrivateKeyGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldPrivateKey, v))
}

// PrivateKeyGTE applies the GTE predicate on the "private_key" field.
func PrivateKeyGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldPrivateKey, v))
}

// PrivateKeyLT applies the LT predicate on the "private_key" field.
func PrivateKeyLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldPrivateKey, v))
}

// PrivateKeyLTE applies the LTE predicate on the "private_key" field.
func PrivateKeyLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldPrivateKey, v))
}

// PrivateKeyContains applies the Contains predicate on the "private_key" field.
func PrivateKeyContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldPrivateKey, v))
}

// PrivateKeyHasPrefix applies the HasPrefix predicate on the "private_key" field.
func PrivateKeyHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldPrivateKey, v))
}

// PrivateKeyHasSuffix applies the HasSuffix predicate on the "private_key" field.
func PrivateKeyHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldPrivateKey, v))
}

// PrivateKeyEqualFold applies the EqualFold predicate on the "private_key" field.
func PrivateKeyEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldPrivateKey, v))
}

// PrivateKeyContainsFold applies the ContainsFold predicate on the "private_key" field.
func PrivateKeyContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldPrivateKey, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldStatus, vs...))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldErrorMessage, v))
}

// ServerGroupIDEQ applies the EQ predicate on the "server_group_id" field.
func ServerGroupIDEQ(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldServerGroupID, v))
}

// ServerGroupIDNEQ applies the NEQ predicate on the "server_group_id" field.
func ServerGroupIDNEQ(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldServerGroupID, v))
}

// ServerGroupIDIn applies the In predicate on the "server_group_id" field.
func ServerGroupIDIn(vs ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldServerGroupID, vs...))
}

// ServerGroupIDNotIn applies the NotIn predicate on the "server_group_id" field.
func ServerGroupIDNotIn(vs ...int) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldServerGroupID, vs...))
}

// ServerGroupIDGT applies the GT predicate on the "server_group_id" field.
func ServerGroupIDGT(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldServerGroupID, v))
}

// ServerGroupIDGTE applies the GTE predicate on the "server_group_id" field.
func ServerGroupIDGTE(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldServerGroupID, v))
}

// ServerGroupIDLT applies the LT predicate on the "server_group_id" field.
func ServerGroupIDLT(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldServerGroupID, v))
}

// ServerGroupIDLTE applies the LTE predicate on the "server_group_id" field.
func ServerGroupIDLTE(v int) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldServerGroupID, v))
}

// ServerGroupIDIsNil applies the IsNil predicate on the "server_group_id" field.
func ServerGroupIDIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldServerGroupID))
}

// ServerGroupIDNotNil applies the NotNil predicate on the "server_group_id" field.
func ServerGroupIDNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldServerGroupID))
}

// AccessIdsIsNil applies the IsNil predicate on the "access_ids" field.
func AccessIdsIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldAccessIds))
}

// AccessIdsNotNil applies the NotNil predicate on the "access_ids" field.
func AccessIdsNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldAccessIds))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDNSProvider applies the HasEdge predicate on the "dns_provider" edge.
func HasDNSProvider() predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DNSProviderTable, DNSProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDNSProviderWith applies the HasEdge predicate on the "dns_provider" edge with a given conditions (other predicates).
func HasDNSProviderWith(preds ...predicate.DNSProvider) predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := newDNSProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAcmeAccount applies the HasEdge predicate on the "acme_account" edge.
func HasAcmeAccount() predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AcmeAccountTable, AcmeAccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAcmeAccountWith applies the HasEdge predicate on the "acme_account" edge with a given conditions (other predicates).
func HasAcmeAccountWith(preds ...predicate.ACMEAccount) predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := newAcmeAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDeployments applies the HasEdge predicate on the "deployments" edge.
func HasDeployments() predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DeploymentsTable, DeploymentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeploymentsWith applies the HasEdge predicate on the "deployments" edge with a given conditions (other predicates).
func HasDeploymentsWith(preds ...predicate.CertificateDeployment) predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := newDeploymentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWorkflowSteps applies the HasEdge predicate on the "workflow_steps" edge.
func HasWorkflowSteps() predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WorkflowStepsTable, WorkflowStepsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkflowStepsWith applies the HasEdge predicate on the "workflow_steps" edge with a given conditions (other predicates).
func HasWorkflowStepsWith(preds ...predicate.WorkflowStep) predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := newWorkflowStepsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWorkflows applies the HasEdge predicate on the "workflows" edge.
func HasWorkflows() predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WorkflowsTable, WorkflowsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkflowsWith applies the HasEdge predicate on the "workflows" edge with a given conditions (other predicates).
func HasWorkflowsWith(preds ...predicate.Workflow) predicate.Certificate {
	return predicate.Certificate(func(s *sql.Selector) {
		step := newWorkflowsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(sql.NotPredicates(p))
}
