// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/certificate"
	"autoSSL/ent/certificatedeployment"
	"autoSSL/ent/servergroup"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CertificateDeployment is the model entity for the CertificateDeployment schema.
type CertificateDeployment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 部署状态
	Status certificatedeployment.Status `json:"status,omitempty"`
	// 部署时间
	DeployedAt time.Time `json:"deployed_at,omitempty"`
	// 部署日志
	Log string `json:"log,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CertificateDeploymentQuery when eager-loading is set.
	Edges                                CertificateDeploymentEdges `json:"edges"`
	certificate_deployments              *int
	server_group_certificate_deployments *int
	selectValues                         sql.SelectValues
}

// CertificateDeploymentEdges holds the relations/edges for other nodes in the graph.
type CertificateDeploymentEdges struct {
	// Certificate holds the value of the certificate edge.
	Certificate *Certificate `json:"certificate,omitempty"`
	// 访问配置
	Access []*Access `json:"access,omitempty"`
	// 关联的服务器组
	ServerGroup *ServerGroup `json:"server_group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// CertificateOrErr returns the Certificate value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CertificateDeploymentEdges) CertificateOrErr() (*Certificate, error) {
	if e.Certificate != nil {
		return e.Certificate, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: certificate.Label}
	}
	return nil, &NotLoadedError{edge: "certificate"}
}

// AccessOrErr returns the Access value or an error if the edge
// was not loaded in eager-loading.
func (e CertificateDeploymentEdges) AccessOrErr() ([]*Access, error) {
	if e.loadedTypes[1] {
		return e.Access, nil
	}
	return nil, &NotLoadedError{edge: "access"}
}

// ServerGroupOrErr returns the ServerGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CertificateDeploymentEdges) ServerGroupOrErr() (*ServerGroup, error) {
	if e.ServerGroup != nil {
		return e.ServerGroup, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: servergroup.Label}
	}
	return nil, &NotLoadedError{edge: "server_group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CertificateDeployment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case certificatedeployment.FieldID:
			values[i] = new(sql.NullInt64)
		case certificatedeployment.FieldStatus, certificatedeployment.FieldLog:
			values[i] = new(sql.NullString)
		case certificatedeployment.FieldDeployedAt, certificatedeployment.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case certificatedeployment.ForeignKeys[0]: // certificate_deployments
			values[i] = new(sql.NullInt64)
		case certificatedeployment.ForeignKeys[1]: // server_group_certificate_deployments
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CertificateDeployment fields.
func (cd *CertificateDeployment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case certificatedeployment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cd.ID = int(value.Int64)
		case certificatedeployment.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				cd.Status = certificatedeployment.Status(value.String)
			}
		case certificatedeployment.FieldDeployedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deployed_at", values[i])
			} else if value.Valid {
				cd.DeployedAt = value.Time
			}
		case certificatedeployment.FieldLog:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field log", values[i])
			} else if value.Valid {
				cd.Log = value.String
			}
		case certificatedeployment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				cd.CreatedAt = value.Time
			}
		case certificatedeployment.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field certificate_deployments", value)
			} else if value.Valid {
				cd.certificate_deployments = new(int)
				*cd.certificate_deployments = int(value.Int64)
			}
		case certificatedeployment.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field server_group_certificate_deployments", value)
			} else if value.Valid {
				cd.server_group_certificate_deployments = new(int)
				*cd.server_group_certificate_deployments = int(value.Int64)
			}
		default:
			cd.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CertificateDeployment.
// This includes values selected through modifiers, order, etc.
func (cd *CertificateDeployment) Value(name string) (ent.Value, error) {
	return cd.selectValues.Get(name)
}

// QueryCertificate queries the "certificate" edge of the CertificateDeployment entity.
func (cd *CertificateDeployment) QueryCertificate() *CertificateQuery {
	return NewCertificateDeploymentClient(cd.config).QueryCertificate(cd)
}

// QueryAccess queries the "access" edge of the CertificateDeployment entity.
func (cd *CertificateDeployment) QueryAccess() *AccessQuery {
	return NewCertificateDeploymentClient(cd.config).QueryAccess(cd)
}

// QueryServerGroup queries the "server_group" edge of the CertificateDeployment entity.
func (cd *CertificateDeployment) QueryServerGroup() *ServerGroupQuery {
	return NewCertificateDeploymentClient(cd.config).QueryServerGroup(cd)
}

// Update returns a builder for updating this CertificateDeployment.
// Note that you need to call CertificateDeployment.Unwrap() before calling this method if this CertificateDeployment
// was returned from a transaction, and the transaction was committed or rolled back.
func (cd *CertificateDeployment) Update() *CertificateDeploymentUpdateOne {
	return NewCertificateDeploymentClient(cd.config).UpdateOne(cd)
}

// Unwrap unwraps the CertificateDeployment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cd *CertificateDeployment) Unwrap() *CertificateDeployment {
	_tx, ok := cd.config.driver.(*txDriver)
	if !ok {
		panic("ent: CertificateDeployment is not a transactional entity")
	}
	cd.config.driver = _tx.drv
	return cd
}

// String implements the fmt.Stringer.
func (cd *CertificateDeployment) String() string {
	var builder strings.Builder
	builder.WriteString("CertificateDeployment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cd.ID))
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", cd.Status))
	builder.WriteString(", ")
	builder.WriteString("deployed_at=")
	builder.WriteString(cd.DeployedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("log=")
	builder.WriteString(cd.Log)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(cd.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CertificateDeployments is a parsable slice of CertificateDeployment.
type CertificateDeployments []*CertificateDeployment
