// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/certificatedeployment"
	"autoSSL/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CertificateDeploymentDelete is the builder for deleting a CertificateDeployment entity.
type CertificateDeploymentDelete struct {
	config
	hooks    []Hook
	mutation *CertificateDeploymentMutation
}

// Where appends a list predicates to the CertificateDeploymentDelete builder.
func (cdd *CertificateDeploymentDelete) Where(ps ...predicate.CertificateDeployment) *CertificateDeploymentDelete {
	cdd.mutation.Where(ps...)
	return cdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cdd *CertificateDeploymentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cdd.sqlExec, cdd.mutation, cdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cdd *CertificateDeploymentDelete) ExecX(ctx context.Context) int {
	n, err := cdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cdd *CertificateDeploymentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(certificatedeployment.Table, sqlgraph.NewFieldSpec(certificatedeployment.FieldID, field.TypeInt))
	if ps := cdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cdd.mutation.done = true
	return affected, err
}

// CertificateDeploymentDeleteOne is the builder for deleting a single CertificateDeployment entity.
type CertificateDeploymentDeleteOne struct {
	cdd *CertificateDeploymentDelete
}

// Where appends a list predicates to the CertificateDeploymentDelete builder.
func (cddo *CertificateDeploymentDeleteOne) Where(ps ...predicate.CertificateDeployment) *CertificateDeploymentDeleteOne {
	cddo.cdd.mutation.Where(ps...)
	return cddo
}

// Exec executes the deletion query.
func (cddo *CertificateDeploymentDeleteOne) Exec(ctx context.Context) error {
	n, err := cddo.cdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{certificatedeployment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cddo *CertificateDeploymentDeleteOne) ExecX(ctx context.Context) {
	if err := cddo.Exec(ctx); err != nil {
		panic(err)
	}
}
