// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/access"
	"autoSSL/ent/certificate"
	"autoSSL/ent/certificatedeployment"
	"autoSSL/ent/servergroup"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CertificateDeploymentCreate is the builder for creating a CertificateDeployment entity.
type CertificateDeploymentCreate struct {
	config
	mutation *CertificateDeploymentMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (cdc *CertificateDeploymentCreate) SetStatus(c certificatedeployment.Status) *CertificateDeploymentCreate {
	cdc.mutation.SetStatus(c)
	return cdc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cdc *CertificateDeploymentCreate) SetNillableStatus(c *certificatedeployment.Status) *CertificateDeploymentCreate {
	if c != nil {
		cdc.SetStatus(*c)
	}
	return cdc
}

// SetDeployedAt sets the "deployed_at" field.
func (cdc *CertificateDeploymentCreate) SetDeployedAt(t time.Time) *CertificateDeploymentCreate {
	cdc.mutation.SetDeployedAt(t)
	return cdc
}

// SetNillableDeployedAt sets the "deployed_at" field if the given value is not nil.
func (cdc *CertificateDeploymentCreate) SetNillableDeployedAt(t *time.Time) *CertificateDeploymentCreate {
	if t != nil {
		cdc.SetDeployedAt(*t)
	}
	return cdc
}

// SetLog sets the "log" field.
func (cdc *CertificateDeploymentCreate) SetLog(s string) *CertificateDeploymentCreate {
	cdc.mutation.SetLog(s)
	return cdc
}

// SetNillableLog sets the "log" field if the given value is not nil.
func (cdc *CertificateDeploymentCreate) SetNillableLog(s *string) *CertificateDeploymentCreate {
	if s != nil {
		cdc.SetLog(*s)
	}
	return cdc
}

// SetCreatedAt sets the "created_at" field.
func (cdc *CertificateDeploymentCreate) SetCreatedAt(t time.Time) *CertificateDeploymentCreate {
	cdc.mutation.SetCreatedAt(t)
	return cdc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cdc *CertificateDeploymentCreate) SetNillableCreatedAt(t *time.Time) *CertificateDeploymentCreate {
	if t != nil {
		cdc.SetCreatedAt(*t)
	}
	return cdc
}

// SetCertificateID sets the "certificate" edge to the Certificate entity by ID.
func (cdc *CertificateDeploymentCreate) SetCertificateID(id int) *CertificateDeploymentCreate {
	cdc.mutation.SetCertificateID(id)
	return cdc
}

// SetCertificate sets the "certificate" edge to the Certificate entity.
func (cdc *CertificateDeploymentCreate) SetCertificate(c *Certificate) *CertificateDeploymentCreate {
	return cdc.SetCertificateID(c.ID)
}

// AddAccesIDs adds the "access" edge to the Access entity by IDs.
func (cdc *CertificateDeploymentCreate) AddAccesIDs(ids ...int) *CertificateDeploymentCreate {
	cdc.mutation.AddAccesIDs(ids...)
	return cdc
}

// AddAccess adds the "access" edges to the Access entity.
func (cdc *CertificateDeploymentCreate) AddAccess(a ...*Access) *CertificateDeploymentCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cdc.AddAccesIDs(ids...)
}

// SetServerGroupID sets the "server_group" edge to the ServerGroup entity by ID.
func (cdc *CertificateDeploymentCreate) SetServerGroupID(id int) *CertificateDeploymentCreate {
	cdc.mutation.SetServerGroupID(id)
	return cdc
}

// SetServerGroup sets the "server_group" edge to the ServerGroup entity.
func (cdc *CertificateDeploymentCreate) SetServerGroup(s *ServerGroup) *CertificateDeploymentCreate {
	return cdc.SetServerGroupID(s.ID)
}

// Mutation returns the CertificateDeploymentMutation object of the builder.
func (cdc *CertificateDeploymentCreate) Mutation() *CertificateDeploymentMutation {
	return cdc.mutation
}

// Save creates the CertificateDeployment in the database.
func (cdc *CertificateDeploymentCreate) Save(ctx context.Context) (*CertificateDeployment, error) {
	cdc.defaults()
	return withHooks(ctx, cdc.sqlSave, cdc.mutation, cdc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cdc *CertificateDeploymentCreate) SaveX(ctx context.Context) *CertificateDeployment {
	v, err := cdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cdc *CertificateDeploymentCreate) Exec(ctx context.Context) error {
	_, err := cdc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cdc *CertificateDeploymentCreate) ExecX(ctx context.Context) {
	if err := cdc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cdc *CertificateDeploymentCreate) defaults() {
	if _, ok := cdc.mutation.Status(); !ok {
		v := certificatedeployment.DefaultStatus
		cdc.mutation.SetStatus(v)
	}
	if _, ok := cdc.mutation.CreatedAt(); !ok {
		v := certificatedeployment.DefaultCreatedAt()
		cdc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cdc *CertificateDeploymentCreate) check() error {
	if _, ok := cdc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CertificateDeployment.status"`)}
	}
	if v, ok := cdc.mutation.Status(); ok {
		if err := certificatedeployment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CertificateDeployment.status": %w`, err)}
		}
	}
	if _, ok := cdc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CertificateDeployment.created_at"`)}
	}
	if len(cdc.mutation.CertificateIDs()) == 0 {
		return &ValidationError{Name: "certificate", err: errors.New(`ent: missing required edge "CertificateDeployment.certificate"`)}
	}
	if len(cdc.mutation.AccessIDs()) == 0 {
		return &ValidationError{Name: "access", err: errors.New(`ent: missing required edge "CertificateDeployment.access"`)}
	}
	if len(cdc.mutation.ServerGroupIDs()) == 0 {
		return &ValidationError{Name: "server_group", err: errors.New(`ent: missing required edge "CertificateDeployment.server_group"`)}
	}
	return nil
}

func (cdc *CertificateDeploymentCreate) sqlSave(ctx context.Context) (*CertificateDeployment, error) {
	if err := cdc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cdc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cdc.mutation.id = &_node.ID
	cdc.mutation.done = true
	return _node, nil
}

func (cdc *CertificateDeploymentCreate) createSpec() (*CertificateDeployment, *sqlgraph.CreateSpec) {
	var (
		_node = &CertificateDeployment{config: cdc.config}
		_spec = sqlgraph.NewCreateSpec(certificatedeployment.Table, sqlgraph.NewFieldSpec(certificatedeployment.FieldID, field.TypeInt))
	)
	if value, ok := cdc.mutation.Status(); ok {
		_spec.SetField(certificatedeployment.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := cdc.mutation.DeployedAt(); ok {
		_spec.SetField(certificatedeployment.FieldDeployedAt, field.TypeTime, value)
		_node.DeployedAt = value
	}
	if value, ok := cdc.mutation.Log(); ok {
		_spec.SetField(certificatedeployment.FieldLog, field.TypeString, value)
		_node.Log = value
	}
	if value, ok := cdc.mutation.CreatedAt(); ok {
		_spec.SetField(certificatedeployment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := cdc.mutation.CertificateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificatedeployment.CertificateTable,
			Columns: []string{certificatedeployment.CertificateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.certificate_deployments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cdc.mutation.AccessIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   certificatedeployment.AccessTable,
			Columns: certificatedeployment.AccessPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cdc.mutation.ServerGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificatedeployment.ServerGroupTable,
			Columns: []string{certificatedeployment.ServerGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servergroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.server_group_certificate_deployments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CertificateDeploymentCreateBulk is the builder for creating many CertificateDeployment entities in bulk.
type CertificateDeploymentCreateBulk struct {
	config
	err      error
	builders []*CertificateDeploymentCreate
}

// Save creates the CertificateDeployment entities in the database.
func (cdcb *CertificateDeploymentCreateBulk) Save(ctx context.Context) ([]*CertificateDeployment, error) {
	if cdcb.err != nil {
		return nil, cdcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cdcb.builders))
	nodes := make([]*CertificateDeployment, len(cdcb.builders))
	mutators := make([]Mutator, len(cdcb.builders))
	for i := range cdcb.builders {
		func(i int, root context.Context) {
			builder := cdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CertificateDeploymentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cdcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cdcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cdcb *CertificateDeploymentCreateBulk) SaveX(ctx context.Context) []*CertificateDeployment {
	v, err := cdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cdcb *CertificateDeploymentCreateBulk) Exec(ctx context.Context) error {
	_, err := cdcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cdcb *CertificateDeploymentCreateBulk) ExecX(ctx context.Context) {
	if err := cdcb.Exec(ctx); err != nil {
		panic(err)
	}
}
