// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/access"
	"autoSSL/ent/certificate"
	"autoSSL/ent/certificatedeployment"
	"autoSSL/ent/predicate"
	"autoSSL/ent/servergroup"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CertificateDeploymentUpdate is the builder for updating CertificateDeployment entities.
type CertificateDeploymentUpdate struct {
	config
	hooks    []Hook
	mutation *CertificateDeploymentMutation
}

// Where appends a list predicates to the CertificateDeploymentUpdate builder.
func (cdu *CertificateDeploymentUpdate) Where(ps ...predicate.CertificateDeployment) *CertificateDeploymentUpdate {
	cdu.mutation.Where(ps...)
	return cdu
}

// SetStatus sets the "status" field.
func (cdu *CertificateDeploymentUpdate) SetStatus(c certificatedeployment.Status) *CertificateDeploymentUpdate {
	cdu.mutation.SetStatus(c)
	return cdu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cdu *CertificateDeploymentUpdate) SetNillableStatus(c *certificatedeployment.Status) *CertificateDeploymentUpdate {
	if c != nil {
		cdu.SetStatus(*c)
	}
	return cdu
}

// SetDeployedAt sets the "deployed_at" field.
func (cdu *CertificateDeploymentUpdate) SetDeployedAt(t time.Time) *CertificateDeploymentUpdate {
	cdu.mutation.SetDeployedAt(t)
	return cdu
}

// SetNillableDeployedAt sets the "deployed_at" field if the given value is not nil.
func (cdu *CertificateDeploymentUpdate) SetNillableDeployedAt(t *time.Time) *CertificateDeploymentUpdate {
	if t != nil {
		cdu.SetDeployedAt(*t)
	}
	return cdu
}

// ClearDeployedAt clears the value of the "deployed_at" field.
func (cdu *CertificateDeploymentUpdate) ClearDeployedAt() *CertificateDeploymentUpdate {
	cdu.mutation.ClearDeployedAt()
	return cdu
}

// SetLog sets the "log" field.
func (cdu *CertificateDeploymentUpdate) SetLog(s string) *CertificateDeploymentUpdate {
	cdu.mutation.SetLog(s)
	return cdu
}

// SetNillableLog sets the "log" field if the given value is not nil.
func (cdu *CertificateDeploymentUpdate) SetNillableLog(s *string) *CertificateDeploymentUpdate {
	if s != nil {
		cdu.SetLog(*s)
	}
	return cdu
}

// ClearLog clears the value of the "log" field.
func (cdu *CertificateDeploymentUpdate) ClearLog() *CertificateDeploymentUpdate {
	cdu.mutation.ClearLog()
	return cdu
}

// SetCertificateID sets the "certificate" edge to the Certificate entity by ID.
func (cdu *CertificateDeploymentUpdate) SetCertificateID(id int) *CertificateDeploymentUpdate {
	cdu.mutation.SetCertificateID(id)
	return cdu
}

// SetCertificate sets the "certificate" edge to the Certificate entity.
func (cdu *CertificateDeploymentUpdate) SetCertificate(c *Certificate) *CertificateDeploymentUpdate {
	return cdu.SetCertificateID(c.ID)
}

// AddAccesIDs adds the "access" edge to the Access entity by IDs.
func (cdu *CertificateDeploymentUpdate) AddAccesIDs(ids ...int) *CertificateDeploymentUpdate {
	cdu.mutation.AddAccesIDs(ids...)
	return cdu
}

// AddAccess adds the "access" edges to the Access entity.
func (cdu *CertificateDeploymentUpdate) AddAccess(a ...*Access) *CertificateDeploymentUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cdu.AddAccesIDs(ids...)
}

// SetServerGroupID sets the "server_group" edge to the ServerGroup entity by ID.
func (cdu *CertificateDeploymentUpdate) SetServerGroupID(id int) *CertificateDeploymentUpdate {
	cdu.mutation.SetServerGroupID(id)
	return cdu
}

// SetServerGroup sets the "server_group" edge to the ServerGroup entity.
func (cdu *CertificateDeploymentUpdate) SetServerGroup(s *ServerGroup) *CertificateDeploymentUpdate {
	return cdu.SetServerGroupID(s.ID)
}

// Mutation returns the CertificateDeploymentMutation object of the builder.
func (cdu *CertificateDeploymentUpdate) Mutation() *CertificateDeploymentMutation {
	return cdu.mutation
}

// ClearCertificate clears the "certificate" edge to the Certificate entity.
func (cdu *CertificateDeploymentUpdate) ClearCertificate() *CertificateDeploymentUpdate {
	cdu.mutation.ClearCertificate()
	return cdu
}

// ClearAccess clears all "access" edges to the Access entity.
func (cdu *CertificateDeploymentUpdate) ClearAccess() *CertificateDeploymentUpdate {
	cdu.mutation.ClearAccess()
	return cdu
}

// RemoveAccesIDs removes the "access" edge to Access entities by IDs.
func (cdu *CertificateDeploymentUpdate) RemoveAccesIDs(ids ...int) *CertificateDeploymentUpdate {
	cdu.mutation.RemoveAccesIDs(ids...)
	return cdu
}

// RemoveAccess removes "access" edges to Access entities.
func (cdu *CertificateDeploymentUpdate) RemoveAccess(a ...*Access) *CertificateDeploymentUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cdu.RemoveAccesIDs(ids...)
}

// ClearServerGroup clears the "server_group" edge to the ServerGroup entity.
func (cdu *CertificateDeploymentUpdate) ClearServerGroup() *CertificateDeploymentUpdate {
	cdu.mutation.ClearServerGroup()
	return cdu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cdu *CertificateDeploymentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cdu.sqlSave, cdu.mutation, cdu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cdu *CertificateDeploymentUpdate) SaveX(ctx context.Context) int {
	affected, err := cdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cdu *CertificateDeploymentUpdate) Exec(ctx context.Context) error {
	_, err := cdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cdu *CertificateDeploymentUpdate) ExecX(ctx context.Context) {
	if err := cdu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cdu *CertificateDeploymentUpdate) check() error {
	if v, ok := cdu.mutation.Status(); ok {
		if err := certificatedeployment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CertificateDeployment.status": %w`, err)}
		}
	}
	if cdu.mutation.CertificateCleared() && len(cdu.mutation.CertificateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CertificateDeployment.certificate"`)
	}
	if cdu.mutation.ServerGroupCleared() && len(cdu.mutation.ServerGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CertificateDeployment.server_group"`)
	}
	return nil
}

func (cdu *CertificateDeploymentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cdu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(certificatedeployment.Table, certificatedeployment.Columns, sqlgraph.NewFieldSpec(certificatedeployment.FieldID, field.TypeInt))
	if ps := cdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cdu.mutation.Status(); ok {
		_spec.SetField(certificatedeployment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := cdu.mutation.DeployedAt(); ok {
		_spec.SetField(certificatedeployment.FieldDeployedAt, field.TypeTime, value)
	}
	if cdu.mutation.DeployedAtCleared() {
		_spec.ClearField(certificatedeployment.FieldDeployedAt, field.TypeTime)
	}
	if value, ok := cdu.mutation.Log(); ok {
		_spec.SetField(certificatedeployment.FieldLog, field.TypeString, value)
	}
	if cdu.mutation.LogCleared() {
		_spec.ClearField(certificatedeployment.FieldLog, field.TypeString)
	}
	if cdu.mutation.CertificateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificatedeployment.CertificateTable,
			Columns: []string{certificatedeployment.CertificateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cdu.mutation.CertificateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificatedeployment.CertificateTable,
			Columns: []string{certificatedeployment.CertificateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cdu.mutation.AccessCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   certificatedeployment.AccessTable,
			Columns: certificatedeployment.AccessPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cdu.mutation.RemovedAccessIDs(); len(nodes) > 0 && !cdu.mutation.AccessCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   certificatedeployment.AccessTable,
			Columns: certificatedeployment.AccessPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cdu.mutation.AccessIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   certificatedeployment.AccessTable,
			Columns: certificatedeployment.AccessPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cdu.mutation.ServerGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificatedeployment.ServerGroupTable,
			Columns: []string{certificatedeployment.ServerGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servergroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cdu.mutation.ServerGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificatedeployment.ServerGroupTable,
			Columns: []string{certificatedeployment.ServerGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servergroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificatedeployment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cdu.mutation.done = true
	return n, nil
}

// CertificateDeploymentUpdateOne is the builder for updating a single CertificateDeployment entity.
type CertificateDeploymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CertificateDeploymentMutation
}

// SetStatus sets the "status" field.
func (cduo *CertificateDeploymentUpdateOne) SetStatus(c certificatedeployment.Status) *CertificateDeploymentUpdateOne {
	cduo.mutation.SetStatus(c)
	return cduo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cduo *CertificateDeploymentUpdateOne) SetNillableStatus(c *certificatedeployment.Status) *CertificateDeploymentUpdateOne {
	if c != nil {
		cduo.SetStatus(*c)
	}
	return cduo
}

// SetDeployedAt sets the "deployed_at" field.
func (cduo *CertificateDeploymentUpdateOne) SetDeployedAt(t time.Time) *CertificateDeploymentUpdateOne {
	cduo.mutation.SetDeployedAt(t)
	return cduo
}

// SetNillableDeployedAt sets the "deployed_at" field if the given value is not nil.
func (cduo *CertificateDeploymentUpdateOne) SetNillableDeployedAt(t *time.Time) *CertificateDeploymentUpdateOne {
	if t != nil {
		cduo.SetDeployedAt(*t)
	}
	return cduo
}

// ClearDeployedAt clears the value of the "deployed_at" field.
func (cduo *CertificateDeploymentUpdateOne) ClearDeployedAt() *CertificateDeploymentUpdateOne {
	cduo.mutation.ClearDeployedAt()
	return cduo
}

// SetLog sets the "log" field.
func (cduo *CertificateDeploymentUpdateOne) SetLog(s string) *CertificateDeploymentUpdateOne {
	cduo.mutation.SetLog(s)
	return cduo
}

// SetNillableLog sets the "log" field if the given value is not nil.
func (cduo *CertificateDeploymentUpdateOne) SetNillableLog(s *string) *CertificateDeploymentUpdateOne {
	if s != nil {
		cduo.SetLog(*s)
	}
	return cduo
}

// ClearLog clears the value of the "log" field.
func (cduo *CertificateDeploymentUpdateOne) ClearLog() *CertificateDeploymentUpdateOne {
	cduo.mutation.ClearLog()
	return cduo
}

// SetCertificateID sets the "certificate" edge to the Certificate entity by ID.
func (cduo *CertificateDeploymentUpdateOne) SetCertificateID(id int) *CertificateDeploymentUpdateOne {
	cduo.mutation.SetCertificateID(id)
	return cduo
}

// SetCertificate sets the "certificate" edge to the Certificate entity.
func (cduo *CertificateDeploymentUpdateOne) SetCertificate(c *Certificate) *CertificateDeploymentUpdateOne {
	return cduo.SetCertificateID(c.ID)
}

// AddAccesIDs adds the "access" edge to the Access entity by IDs.
func (cduo *CertificateDeploymentUpdateOne) AddAccesIDs(ids ...int) *CertificateDeploymentUpdateOne {
	cduo.mutation.AddAccesIDs(ids...)
	return cduo
}

// AddAccess adds the "access" edges to the Access entity.
func (cduo *CertificateDeploymentUpdateOne) AddAccess(a ...*Access) *CertificateDeploymentUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cduo.AddAccesIDs(ids...)
}

// SetServerGroupID sets the "server_group" edge to the ServerGroup entity by ID.
func (cduo *CertificateDeploymentUpdateOne) SetServerGroupID(id int) *CertificateDeploymentUpdateOne {
	cduo.mutation.SetServerGroupID(id)
	return cduo
}

// SetServerGroup sets the "server_group" edge to the ServerGroup entity.
func (cduo *CertificateDeploymentUpdateOne) SetServerGroup(s *ServerGroup) *CertificateDeploymentUpdateOne {
	return cduo.SetServerGroupID(s.ID)
}

// Mutation returns the CertificateDeploymentMutation object of the builder.
func (cduo *CertificateDeploymentUpdateOne) Mutation() *CertificateDeploymentMutation {
	return cduo.mutation
}

// ClearCertificate clears the "certificate" edge to the Certificate entity.
func (cduo *CertificateDeploymentUpdateOne) ClearCertificate() *CertificateDeploymentUpdateOne {
	cduo.mutation.ClearCertificate()
	return cduo
}

// ClearAccess clears all "access" edges to the Access entity.
func (cduo *CertificateDeploymentUpdateOne) ClearAccess() *CertificateDeploymentUpdateOne {
	cduo.mutation.ClearAccess()
	return cduo
}

// RemoveAccesIDs removes the "access" edge to Access entities by IDs.
func (cduo *CertificateDeploymentUpdateOne) RemoveAccesIDs(ids ...int) *CertificateDeploymentUpdateOne {
	cduo.mutation.RemoveAccesIDs(ids...)
	return cduo
}

// RemoveAccess removes "access" edges to Access entities.
func (cduo *CertificateDeploymentUpdateOne) RemoveAccess(a ...*Access) *CertificateDeploymentUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cduo.RemoveAccesIDs(ids...)
}

// ClearServerGroup clears the "server_group" edge to the ServerGroup entity.
func (cduo *CertificateDeploymentUpdateOne) ClearServerGroup() *CertificateDeploymentUpdateOne {
	cduo.mutation.ClearServerGroup()
	return cduo
}

// Where appends a list predicates to the CertificateDeploymentUpdate builder.
func (cduo *CertificateDeploymentUpdateOne) Where(ps ...predicate.CertificateDeployment) *CertificateDeploymentUpdateOne {
	cduo.mutation.Where(ps...)
	return cduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cduo *CertificateDeploymentUpdateOne) Select(field string, fields ...string) *CertificateDeploymentUpdateOne {
	cduo.fields = append([]string{field}, fields...)
	return cduo
}

// Save executes the query and returns the updated CertificateDeployment entity.
func (cduo *CertificateDeploymentUpdateOne) Save(ctx context.Context) (*CertificateDeployment, error) {
	return withHooks(ctx, cduo.sqlSave, cduo.mutation, cduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cduo *CertificateDeploymentUpdateOne) SaveX(ctx context.Context) *CertificateDeployment {
	node, err := cduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cduo *CertificateDeploymentUpdateOne) Exec(ctx context.Context) error {
	_, err := cduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cduo *CertificateDeploymentUpdateOne) ExecX(ctx context.Context) {
	if err := cduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cduo *CertificateDeploymentUpdateOne) check() error {
	if v, ok := cduo.mutation.Status(); ok {
		if err := certificatedeployment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CertificateDeployment.status": %w`, err)}
		}
	}
	if cduo.mutation.CertificateCleared() && len(cduo.mutation.CertificateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CertificateDeployment.certificate"`)
	}
	if cduo.mutation.ServerGroupCleared() && len(cduo.mutation.ServerGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CertificateDeployment.server_group"`)
	}
	return nil
}

func (cduo *CertificateDeploymentUpdateOne) sqlSave(ctx context.Context) (_node *CertificateDeployment, err error) {
	if err := cduo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(certificatedeployment.Table, certificatedeployment.Columns, sqlgraph.NewFieldSpec(certificatedeployment.FieldID, field.TypeInt))
	id, ok := cduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CertificateDeployment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, certificatedeployment.FieldID)
		for _, f := range fields {
			if !certificatedeployment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != certificatedeployment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cduo.mutation.Status(); ok {
		_spec.SetField(certificatedeployment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := cduo.mutation.DeployedAt(); ok {
		_spec.SetField(certificatedeployment.FieldDeployedAt, field.TypeTime, value)
	}
	if cduo.mutation.DeployedAtCleared() {
		_spec.ClearField(certificatedeployment.FieldDeployedAt, field.TypeTime)
	}
	if value, ok := cduo.mutation.Log(); ok {
		_spec.SetField(certificatedeployment.FieldLog, field.TypeString, value)
	}
	if cduo.mutation.LogCleared() {
		_spec.ClearField(certificatedeployment.FieldLog, field.TypeString)
	}
	if cduo.mutation.CertificateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificatedeployment.CertificateTable,
			Columns: []string{certificatedeployment.CertificateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cduo.mutation.CertificateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificatedeployment.CertificateTable,
			Columns: []string{certificatedeployment.CertificateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cduo.mutation.AccessCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   certificatedeployment.AccessTable,
			Columns: certificatedeployment.AccessPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cduo.mutation.RemovedAccessIDs(); len(nodes) > 0 && !cduo.mutation.AccessCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   certificatedeployment.AccessTable,
			Columns: certificatedeployment.AccessPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cduo.mutation.AccessIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   certificatedeployment.AccessTable,
			Columns: certificatedeployment.AccessPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cduo.mutation.ServerGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificatedeployment.ServerGroupTable,
			Columns: []string{certificatedeployment.ServerGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servergroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cduo.mutation.ServerGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificatedeployment.ServerGroupTable,
			Columns: []string{certificatedeployment.ServerGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servergroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CertificateDeployment{config: cduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificatedeployment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cduo.mutation.done = true
	return _node, nil
}
