// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/certificate"
	"autoSSL/ent/dnsprovider"
	"autoSSL/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DNSProviderCreate is the builder for creating a DNSProvider entity.
type DNSProviderCreate struct {
	config
	mutation *DNSProviderMutation
	hooks    []Hook
}

// SetProviderType sets the "provider_type" field.
func (dpc *DNSProviderCreate) SetProviderType(dt dnsprovider.ProviderType) *DNSProviderCreate {
	dpc.mutation.SetProviderType(dt)
	return dpc
}

// SetConfig sets the "config" field.
func (dpc *DNSProviderCreate) SetConfig(m map[string]interface{}) *DNSProviderCreate {
	dpc.mutation.SetConfig(m)
	return dpc
}

// SetCreatedAt sets the "created_at" field.
func (dpc *DNSProviderCreate) SetCreatedAt(t time.Time) *DNSProviderCreate {
	dpc.mutation.SetCreatedAt(t)
	return dpc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (dpc *DNSProviderCreate) SetNillableCreatedAt(t *time.Time) *DNSProviderCreate {
	if t != nil {
		dpc.SetCreatedAt(*t)
	}
	return dpc
}

// SetUpdatedAt sets the "updated_at" field.
func (dpc *DNSProviderCreate) SetUpdatedAt(t time.Time) *DNSProviderCreate {
	dpc.mutation.SetUpdatedAt(t)
	return dpc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (dpc *DNSProviderCreate) SetNillableUpdatedAt(t *time.Time) *DNSProviderCreate {
	if t != nil {
		dpc.SetUpdatedAt(*t)
	}
	return dpc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (dpc *DNSProviderCreate) SetUserID(id int) *DNSProviderCreate {
	dpc.mutation.SetUserID(id)
	return dpc
}

// SetUser sets the "user" edge to the User entity.
func (dpc *DNSProviderCreate) SetUser(u *User) *DNSProviderCreate {
	return dpc.SetUserID(u.ID)
}

// AddCertificateIDs adds the "certificates" edge to the Certificate entity by IDs.
func (dpc *DNSProviderCreate) AddCertificateIDs(ids ...int) *DNSProviderCreate {
	dpc.mutation.AddCertificateIDs(ids...)
	return dpc
}

// AddCertificates adds the "certificates" edges to the Certificate entity.
func (dpc *DNSProviderCreate) AddCertificates(c ...*Certificate) *DNSProviderCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return dpc.AddCertificateIDs(ids...)
}

// Mutation returns the DNSProviderMutation object of the builder.
func (dpc *DNSProviderCreate) Mutation() *DNSProviderMutation {
	return dpc.mutation
}

// Save creates the DNSProvider in the database.
func (dpc *DNSProviderCreate) Save(ctx context.Context) (*DNSProvider, error) {
	dpc.defaults()
	return withHooks(ctx, dpc.sqlSave, dpc.mutation, dpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dpc *DNSProviderCreate) SaveX(ctx context.Context) *DNSProvider {
	v, err := dpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dpc *DNSProviderCreate) Exec(ctx context.Context) error {
	_, err := dpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dpc *DNSProviderCreate) ExecX(ctx context.Context) {
	if err := dpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dpc *DNSProviderCreate) defaults() {
	if _, ok := dpc.mutation.CreatedAt(); !ok {
		v := dnsprovider.DefaultCreatedAt()
		dpc.mutation.SetCreatedAt(v)
	}
	if _, ok := dpc.mutation.UpdatedAt(); !ok {
		v := dnsprovider.DefaultUpdatedAt()
		dpc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dpc *DNSProviderCreate) check() error {
	if _, ok := dpc.mutation.ProviderType(); !ok {
		return &ValidationError{Name: "provider_type", err: errors.New(`ent: missing required field "DNSProvider.provider_type"`)}
	}
	if v, ok := dpc.mutation.ProviderType(); ok {
		if err := dnsprovider.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "DNSProvider.provider_type": %w`, err)}
		}
	}
	if _, ok := dpc.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "DNSProvider.config"`)}
	}
	if _, ok := dpc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DNSProvider.created_at"`)}
	}
	if _, ok := dpc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DNSProvider.updated_at"`)}
	}
	if len(dpc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "DNSProvider.user"`)}
	}
	return nil
}

func (dpc *DNSProviderCreate) sqlSave(ctx context.Context) (*DNSProvider, error) {
	if err := dpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	dpc.mutation.id = &_node.ID
	dpc.mutation.done = true
	return _node, nil
}

func (dpc *DNSProviderCreate) createSpec() (*DNSProvider, *sqlgraph.CreateSpec) {
	var (
		_node = &DNSProvider{config: dpc.config}
		_spec = sqlgraph.NewCreateSpec(dnsprovider.Table, sqlgraph.NewFieldSpec(dnsprovider.FieldID, field.TypeInt))
	)
	if value, ok := dpc.mutation.ProviderType(); ok {
		_spec.SetField(dnsprovider.FieldProviderType, field.TypeEnum, value)
		_node.ProviderType = value
	}
	if value, ok := dpc.mutation.Config(); ok {
		_spec.SetField(dnsprovider.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := dpc.mutation.CreatedAt(); ok {
		_spec.SetField(dnsprovider.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := dpc.mutation.UpdatedAt(); ok {
		_spec.SetField(dnsprovider.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := dpc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dnsprovider.UserTable,
			Columns: []string{dnsprovider.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_dns_providers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dpc.mutation.CertificatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnsprovider.CertificatesTable,
			Columns: []string{dnsprovider.CertificatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DNSProviderCreateBulk is the builder for creating many DNSProvider entities in bulk.
type DNSProviderCreateBulk struct {
	config
	err      error
	builders []*DNSProviderCreate
}

// Save creates the DNSProvider entities in the database.
func (dpcb *DNSProviderCreateBulk) Save(ctx context.Context) ([]*DNSProvider, error) {
	if dpcb.err != nil {
		return nil, dpcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dpcb.builders))
	nodes := make([]*DNSProvider, len(dpcb.builders))
	mutators := make([]Mutator, len(dpcb.builders))
	for i := range dpcb.builders {
		func(i int, root context.Context) {
			builder := dpcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DNSProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dpcb *DNSProviderCreateBulk) SaveX(ctx context.Context) []*DNSProvider {
	v, err := dpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dpcb *DNSProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := dpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dpcb *DNSProviderCreateBulk) ExecX(ctx context.Context) {
	if err := dpcb.Exec(ctx); err != nil {
		panic(err)
	}
}
