// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/globalnotificationconfig"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GlobalNotificationConfig is the model entity for the GlobalNotificationConfig schema.
type GlobalNotificationConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 配置名称，如：platform_email, platform_sms
	Name string `json:"name,omitempty"`
	// 通知类型：email或sms
	Type globalnotificationconfig.Type `json:"type,omitempty"`
	// 全局通知配置参数(JSON格式)
	// 				- email: {smtp_server:string, smtp_port:int, username:string, password:string, from:string, from_name:string}
	// 				- sms: {api_key:string, api_secret:string, sign_name:string, template_code:string}
	Config map[string]interface{} `json:"config,omitempty"`
	// 是否启用
	IsActive bool `json:"is_active,omitempty"`
	// 配置描述
	Description string `json:"description,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GlobalNotificationConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case globalnotificationconfig.FieldConfig:
			values[i] = new([]byte)
		case globalnotificationconfig.FieldIsActive:
			values[i] = new(sql.NullBool)
		case globalnotificationconfig.FieldID:
			values[i] = new(sql.NullInt64)
		case globalnotificationconfig.FieldName, globalnotificationconfig.FieldType, globalnotificationconfig.FieldDescription:
			values[i] = new(sql.NullString)
		case globalnotificationconfig.FieldCreatedAt, globalnotificationconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GlobalNotificationConfig fields.
func (gnc *GlobalNotificationConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case globalnotificationconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			gnc.ID = int(value.Int64)
		case globalnotificationconfig.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				gnc.Name = value.String
			}
		case globalnotificationconfig.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				gnc.Type = globalnotificationconfig.Type(value.String)
			}
		case globalnotificationconfig.FieldConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &gnc.Config); err != nil {
					return fmt.Errorf("unmarshal field config: %w", err)
				}
			}
		case globalnotificationconfig.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				gnc.IsActive = value.Bool
			}
		case globalnotificationconfig.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				gnc.Description = value.String
			}
		case globalnotificationconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				gnc.CreatedAt = value.Time
			}
		case globalnotificationconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				gnc.UpdatedAt = value.Time
			}
		default:
			gnc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GlobalNotificationConfig.
// This includes values selected through modifiers, order, etc.
func (gnc *GlobalNotificationConfig) Value(name string) (ent.Value, error) {
	return gnc.selectValues.Get(name)
}

// Update returns a builder for updating this GlobalNotificationConfig.
// Note that you need to call GlobalNotificationConfig.Unwrap() before calling this method if this GlobalNotificationConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (gnc *GlobalNotificationConfig) Update() *GlobalNotificationConfigUpdateOne {
	return NewGlobalNotificationConfigClient(gnc.config).UpdateOne(gnc)
}

// Unwrap unwraps the GlobalNotificationConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (gnc *GlobalNotificationConfig) Unwrap() *GlobalNotificationConfig {
	_tx, ok := gnc.config.driver.(*txDriver)
	if !ok {
		panic("ent: GlobalNotificationConfig is not a transactional entity")
	}
	gnc.config.driver = _tx.drv
	return gnc
}

// String implements the fmt.Stringer.
func (gnc *GlobalNotificationConfig) String() string {
	var builder strings.Builder
	builder.WriteString("GlobalNotificationConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", gnc.ID))
	builder.WriteString("name=")
	builder.WriteString(gnc.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", gnc.Type))
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(fmt.Sprintf("%v", gnc.Config))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", gnc.IsActive))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(gnc.Description)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(gnc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(gnc.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GlobalNotificationConfigs is a parsable slice of GlobalNotificationConfig.
type GlobalNotificationConfigs []*GlobalNotificationConfig
