// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/globalnotificationconfig"
	"autoSSL/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GlobalNotificationConfigDelete is the builder for deleting a GlobalNotificationConfig entity.
type GlobalNotificationConfigDelete struct {
	config
	hooks    []Hook
	mutation *GlobalNotificationConfigMutation
}

// Where appends a list predicates to the GlobalNotificationConfigDelete builder.
func (gncd *GlobalNotificationConfigDelete) Where(ps ...predicate.GlobalNotificationConfig) *GlobalNotificationConfigDelete {
	gncd.mutation.Where(ps...)
	return gncd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gncd *GlobalNotificationConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, gncd.sqlExec, gncd.mutation, gncd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (gncd *GlobalNotificationConfigDelete) ExecX(ctx context.Context) int {
	n, err := gncd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gncd *GlobalNotificationConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(globalnotificationconfig.Table, sqlgraph.NewFieldSpec(globalnotificationconfig.FieldID, field.TypeInt))
	if ps := gncd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gncd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	gncd.mutation.done = true
	return affected, err
}

// GlobalNotificationConfigDeleteOne is the builder for deleting a single GlobalNotificationConfig entity.
type GlobalNotificationConfigDeleteOne struct {
	gncd *GlobalNotificationConfigDelete
}

// Where appends a list predicates to the GlobalNotificationConfigDelete builder.
func (gncdo *GlobalNotificationConfigDeleteOne) Where(ps ...predicate.GlobalNotificationConfig) *GlobalNotificationConfigDeleteOne {
	gncdo.gncd.mutation.Where(ps...)
	return gncdo
}

// Exec executes the deletion query.
func (gncdo *GlobalNotificationConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := gncdo.gncd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{globalnotificationconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gncdo *GlobalNotificationConfigDeleteOne) ExecX(ctx context.Context) {
	if err := gncdo.Exec(ctx); err != nil {
		panic(err)
	}
}
