// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/notificationconfig"
	"autoSSL/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationConfigCreate is the builder for creating a NotificationConfig entity.
type NotificationConfigCreate struct {
	config
	mutation *NotificationConfigMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ncc *NotificationConfigCreate) SetName(s string) *NotificationConfigCreate {
	ncc.mutation.SetName(s)
	return ncc
}

// SetType sets the "type" field.
func (ncc *NotificationConfigCreate) SetType(n notificationconfig.Type) *NotificationConfigCreate {
	ncc.mutation.SetType(n)
	return ncc
}

// SetConfig sets the "config" field.
func (ncc *NotificationConfigCreate) SetConfig(m map[string]interface{}) *NotificationConfigCreate {
	ncc.mutation.SetConfig(m)
	return ncc
}

// SetIsActive sets the "is_active" field.
func (ncc *NotificationConfigCreate) SetIsActive(b bool) *NotificationConfigCreate {
	ncc.mutation.SetIsActive(b)
	return ncc
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (ncc *NotificationConfigCreate) SetNillableIsActive(b *bool) *NotificationConfigCreate {
	if b != nil {
		ncc.SetIsActive(*b)
	}
	return ncc
}

// SetCreatedAt sets the "created_at" field.
func (ncc *NotificationConfigCreate) SetCreatedAt(t time.Time) *NotificationConfigCreate {
	ncc.mutation.SetCreatedAt(t)
	return ncc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ncc *NotificationConfigCreate) SetNillableCreatedAt(t *time.Time) *NotificationConfigCreate {
	if t != nil {
		ncc.SetCreatedAt(*t)
	}
	return ncc
}

// SetUpdatedAt sets the "updated_at" field.
func (ncc *NotificationConfigCreate) SetUpdatedAt(t time.Time) *NotificationConfigCreate {
	ncc.mutation.SetUpdatedAt(t)
	return ncc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ncc *NotificationConfigCreate) SetNillableUpdatedAt(t *time.Time) *NotificationConfigCreate {
	if t != nil {
		ncc.SetUpdatedAt(*t)
	}
	return ncc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ncc *NotificationConfigCreate) SetUserID(id int) *NotificationConfigCreate {
	ncc.mutation.SetUserID(id)
	return ncc
}

// SetUser sets the "user" edge to the User entity.
func (ncc *NotificationConfigCreate) SetUser(u *User) *NotificationConfigCreate {
	return ncc.SetUserID(u.ID)
}

// Mutation returns the NotificationConfigMutation object of the builder.
func (ncc *NotificationConfigCreate) Mutation() *NotificationConfigMutation {
	return ncc.mutation
}

// Save creates the NotificationConfig in the database.
func (ncc *NotificationConfigCreate) Save(ctx context.Context) (*NotificationConfig, error) {
	ncc.defaults()
	return withHooks(ctx, ncc.sqlSave, ncc.mutation, ncc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ncc *NotificationConfigCreate) SaveX(ctx context.Context) *NotificationConfig {
	v, err := ncc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncc *NotificationConfigCreate) Exec(ctx context.Context) error {
	_, err := ncc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncc *NotificationConfigCreate) ExecX(ctx context.Context) {
	if err := ncc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ncc *NotificationConfigCreate) defaults() {
	if _, ok := ncc.mutation.IsActive(); !ok {
		v := notificationconfig.DefaultIsActive
		ncc.mutation.SetIsActive(v)
	}
	if _, ok := ncc.mutation.CreatedAt(); !ok {
		v := notificationconfig.DefaultCreatedAt()
		ncc.mutation.SetCreatedAt(v)
	}
	if _, ok := ncc.mutation.UpdatedAt(); !ok {
		v := notificationconfig.DefaultUpdatedAt()
		ncc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ncc *NotificationConfigCreate) check() error {
	if _, ok := ncc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "NotificationConfig.name"`)}
	}
	if _, ok := ncc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "NotificationConfig.type"`)}
	}
	if v, ok := ncc.mutation.GetType(); ok {
		if err := notificationconfig.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "NotificationConfig.type": %w`, err)}
		}
	}
	if _, ok := ncc.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "NotificationConfig.config"`)}
	}
	if _, ok := ncc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "NotificationConfig.is_active"`)}
	}
	if _, ok := ncc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NotificationConfig.created_at"`)}
	}
	if _, ok := ncc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NotificationConfig.updated_at"`)}
	}
	if len(ncc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "NotificationConfig.user"`)}
	}
	return nil
}

func (ncc *NotificationConfigCreate) sqlSave(ctx context.Context) (*NotificationConfig, error) {
	if err := ncc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ncc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ncc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ncc.mutation.id = &_node.ID
	ncc.mutation.done = true
	return _node, nil
}

func (ncc *NotificationConfigCreate) createSpec() (*NotificationConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationConfig{config: ncc.config}
		_spec = sqlgraph.NewCreateSpec(notificationconfig.Table, sqlgraph.NewFieldSpec(notificationconfig.FieldID, field.TypeInt))
	)
	if value, ok := ncc.mutation.Name(); ok {
		_spec.SetField(notificationconfig.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ncc.mutation.GetType(); ok {
		_spec.SetField(notificationconfig.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := ncc.mutation.Config(); ok {
		_spec.SetField(notificationconfig.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := ncc.mutation.IsActive(); ok {
		_spec.SetField(notificationconfig.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := ncc.mutation.CreatedAt(); ok {
		_spec.SetField(notificationconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ncc.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := ncc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationconfig.UserTable,
			Columns: []string{notificationconfig.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_notification_configs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NotificationConfigCreateBulk is the builder for creating many NotificationConfig entities in bulk.
type NotificationConfigCreateBulk struct {
	config
	err      error
	builders []*NotificationConfigCreate
}

// Save creates the NotificationConfig entities in the database.
func (nccb *NotificationConfigCreateBulk) Save(ctx context.Context) ([]*NotificationConfig, error) {
	if nccb.err != nil {
		return nil, nccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(nccb.builders))
	nodes := make([]*NotificationConfig, len(nccb.builders))
	mutators := make([]Mutator, len(nccb.builders))
	for i := range nccb.builders {
		func(i int, root context.Context) {
			builder := nccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, nccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, nccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, nccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (nccb *NotificationConfigCreateBulk) SaveX(ctx context.Context) []*NotificationConfig {
	v, err := nccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nccb *NotificationConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := nccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nccb *NotificationConfigCreateBulk) ExecX(ctx context.Context) {
	if err := nccb.Exec(ctx); err != nil {
		panic(err)
	}
}
