// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/notificationtemplate"
	"autoSSL/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationTemplateUpdate is the builder for updating NotificationTemplate entities.
type NotificationTemplateUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationTemplateMutation
}

// Where appends a list predicates to the NotificationTemplateUpdate builder.
func (ntu *NotificationTemplateUpdate) Where(ps ...predicate.NotificationTemplate) *NotificationTemplateUpdate {
	ntu.mutation.Where(ps...)
	return ntu
}

// SetName sets the "name" field.
func (ntu *NotificationTemplateUpdate) SetName(s string) *NotificationTemplateUpdate {
	ntu.mutation.SetName(s)
	return ntu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ntu *NotificationTemplateUpdate) SetNillableName(s *string) *NotificationTemplateUpdate {
	if s != nil {
		ntu.SetName(*s)
	}
	return ntu
}

// SetType sets the "type" field.
func (ntu *NotificationTemplateUpdate) SetType(s string) *NotificationTemplateUpdate {
	ntu.mutation.SetType(s)
	return ntu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (ntu *NotificationTemplateUpdate) SetNillableType(s *string) *NotificationTemplateUpdate {
	if s != nil {
		ntu.SetType(*s)
	}
	return ntu
}

// SetSubjectTemplate sets the "subject_template" field.
func (ntu *NotificationTemplateUpdate) SetSubjectTemplate(s string) *NotificationTemplateUpdate {
	ntu.mutation.SetSubjectTemplate(s)
	return ntu
}

// SetNillableSubjectTemplate sets the "subject_template" field if the given value is not nil.
func (ntu *NotificationTemplateUpdate) SetNillableSubjectTemplate(s *string) *NotificationTemplateUpdate {
	if s != nil {
		ntu.SetSubjectTemplate(*s)
	}
	return ntu
}

// ClearSubjectTemplate clears the value of the "subject_template" field.
func (ntu *NotificationTemplateUpdate) ClearSubjectTemplate() *NotificationTemplateUpdate {
	ntu.mutation.ClearSubjectTemplate()
	return ntu
}

// SetContentTemplate sets the "content_template" field.
func (ntu *NotificationTemplateUpdate) SetContentTemplate(s string) *NotificationTemplateUpdate {
	ntu.mutation.SetContentTemplate(s)
	return ntu
}

// SetNillableContentTemplate sets the "content_template" field if the given value is not nil.
func (ntu *NotificationTemplateUpdate) SetNillableContentTemplate(s *string) *NotificationTemplateUpdate {
	if s != nil {
		ntu.SetContentTemplate(*s)
	}
	return ntu
}

// SetFormat sets the "format" field.
func (ntu *NotificationTemplateUpdate) SetFormat(s string) *NotificationTemplateUpdate {
	ntu.mutation.SetFormat(s)
	return ntu
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (ntu *NotificationTemplateUpdate) SetNillableFormat(s *string) *NotificationTemplateUpdate {
	if s != nil {
		ntu.SetFormat(*s)
	}
	return ntu
}

// SetUserID sets the "user_id" field.
func (ntu *NotificationTemplateUpdate) SetUserID(i int) *NotificationTemplateUpdate {
	ntu.mutation.ResetUserID()
	ntu.mutation.SetUserID(i)
	return ntu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ntu *NotificationTemplateUpdate) SetNillableUserID(i *int) *NotificationTemplateUpdate {
	if i != nil {
		ntu.SetUserID(*i)
	}
	return ntu
}

// AddUserID adds i to the "user_id" field.
func (ntu *NotificationTemplateUpdate) AddUserID(i int) *NotificationTemplateUpdate {
	ntu.mutation.AddUserID(i)
	return ntu
}

// ClearUserID clears the value of the "user_id" field.
func (ntu *NotificationTemplateUpdate) ClearUserID() *NotificationTemplateUpdate {
	ntu.mutation.ClearUserID()
	return ntu
}

// SetIsSystemDefault sets the "is_system_default" field.
func (ntu *NotificationTemplateUpdate) SetIsSystemDefault(b bool) *NotificationTemplateUpdate {
	ntu.mutation.SetIsSystemDefault(b)
	return ntu
}

// SetNillableIsSystemDefault sets the "is_system_default" field if the given value is not nil.
func (ntu *NotificationTemplateUpdate) SetNillableIsSystemDefault(b *bool) *NotificationTemplateUpdate {
	if b != nil {
		ntu.SetIsSystemDefault(*b)
	}
	return ntu
}

// SetIsActive sets the "is_active" field.
func (ntu *NotificationTemplateUpdate) SetIsActive(b bool) *NotificationTemplateUpdate {
	ntu.mutation.SetIsActive(b)
	return ntu
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (ntu *NotificationTemplateUpdate) SetNillableIsActive(b *bool) *NotificationTemplateUpdate {
	if b != nil {
		ntu.SetIsActive(*b)
	}
	return ntu
}

// SetCreatedAt sets the "created_at" field.
func (ntu *NotificationTemplateUpdate) SetCreatedAt(t time.Time) *NotificationTemplateUpdate {
	ntu.mutation.SetCreatedAt(t)
	return ntu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ntu *NotificationTemplateUpdate) SetNillableCreatedAt(t *time.Time) *NotificationTemplateUpdate {
	if t != nil {
		ntu.SetCreatedAt(*t)
	}
	return ntu
}

// SetUpdatedAt sets the "updated_at" field.
func (ntu *NotificationTemplateUpdate) SetUpdatedAt(t time.Time) *NotificationTemplateUpdate {
	ntu.mutation.SetUpdatedAt(t)
	return ntu
}

// Mutation returns the NotificationTemplateMutation object of the builder.
func (ntu *NotificationTemplateUpdate) Mutation() *NotificationTemplateMutation {
	return ntu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ntu *NotificationTemplateUpdate) Save(ctx context.Context) (int, error) {
	ntu.defaults()
	return withHooks(ctx, ntu.sqlSave, ntu.mutation, ntu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ntu *NotificationTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := ntu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ntu *NotificationTemplateUpdate) Exec(ctx context.Context) error {
	_, err := ntu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ntu *NotificationTemplateUpdate) ExecX(ctx context.Context) {
	if err := ntu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ntu *NotificationTemplateUpdate) defaults() {
	if _, ok := ntu.mutation.UpdatedAt(); !ok {
		v := notificationtemplate.UpdateDefaultUpdatedAt()
		ntu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ntu *NotificationTemplateUpdate) check() error {
	if v, ok := ntu.mutation.Name(); ok {
		if err := notificationtemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationTemplate.name": %w`, err)}
		}
	}
	if v, ok := ntu.mutation.GetType(); ok {
		if err := notificationtemplate.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "NotificationTemplate.type": %w`, err)}
		}
	}
	if v, ok := ntu.mutation.ContentTemplate(); ok {
		if err := notificationtemplate.ContentTemplateValidator(v); err != nil {
			return &ValidationError{Name: "content_template", err: fmt.Errorf(`ent: validator failed for field "NotificationTemplate.content_template": %w`, err)}
		}
	}
	return nil
}

func (ntu *NotificationTemplateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ntu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationtemplate.Table, notificationtemplate.Columns, sqlgraph.NewFieldSpec(notificationtemplate.FieldID, field.TypeInt))
	if ps := ntu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ntu.mutation.Name(); ok {
		_spec.SetField(notificationtemplate.FieldName, field.TypeString, value)
	}
	if value, ok := ntu.mutation.GetType(); ok {
		_spec.SetField(notificationtemplate.FieldType, field.TypeString, value)
	}
	if value, ok := ntu.mutation.SubjectTemplate(); ok {
		_spec.SetField(notificationtemplate.FieldSubjectTemplate, field.TypeString, value)
	}
	if ntu.mutation.SubjectTemplateCleared() {
		_spec.ClearField(notificationtemplate.FieldSubjectTemplate, field.TypeString)
	}
	if value, ok := ntu.mutation.ContentTemplate(); ok {
		_spec.SetField(notificationtemplate.FieldContentTemplate, field.TypeString, value)
	}
	if value, ok := ntu.mutation.Format(); ok {
		_spec.SetField(notificationtemplate.FieldFormat, field.TypeString, value)
	}
	if value, ok := ntu.mutation.UserID(); ok {
		_spec.SetField(notificationtemplate.FieldUserID, field.TypeInt, value)
	}
	if value, ok := ntu.mutation.AddedUserID(); ok {
		_spec.AddField(notificationtemplate.FieldUserID, field.TypeInt, value)
	}
	if ntu.mutation.UserIDCleared() {
		_spec.ClearField(notificationtemplate.FieldUserID, field.TypeInt)
	}
	if value, ok := ntu.mutation.IsSystemDefault(); ok {
		_spec.SetField(notificationtemplate.FieldIsSystemDefault, field.TypeBool, value)
	}
	if value, ok := ntu.mutation.IsActive(); ok {
		_spec.SetField(notificationtemplate.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := ntu.mutation.CreatedAt(); ok {
		_spec.SetField(notificationtemplate.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := ntu.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationtemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ntu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ntu.mutation.done = true
	return n, nil
}

// NotificationTemplateUpdateOne is the builder for updating a single NotificationTemplate entity.
type NotificationTemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationTemplateMutation
}

// SetName sets the "name" field.
func (ntuo *NotificationTemplateUpdateOne) SetName(s string) *NotificationTemplateUpdateOne {
	ntuo.mutation.SetName(s)
	return ntuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ntuo *NotificationTemplateUpdateOne) SetNillableName(s *string) *NotificationTemplateUpdateOne {
	if s != nil {
		ntuo.SetName(*s)
	}
	return ntuo
}

// SetType sets the "type" field.
func (ntuo *NotificationTemplateUpdateOne) SetType(s string) *NotificationTemplateUpdateOne {
	ntuo.mutation.SetType(s)
	return ntuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (ntuo *NotificationTemplateUpdateOne) SetNillableType(s *string) *NotificationTemplateUpdateOne {
	if s != nil {
		ntuo.SetType(*s)
	}
	return ntuo
}

// SetSubjectTemplate sets the "subject_template" field.
func (ntuo *NotificationTemplateUpdateOne) SetSubjectTemplate(s string) *NotificationTemplateUpdateOne {
	ntuo.mutation.SetSubjectTemplate(s)
	return ntuo
}

// SetNillableSubjectTemplate sets the "subject_template" field if the given value is not nil.
func (ntuo *NotificationTemplateUpdateOne) SetNillableSubjectTemplate(s *string) *NotificationTemplateUpdateOne {
	if s != nil {
		ntuo.SetSubjectTemplate(*s)
	}
	return ntuo
}

// ClearSubjectTemplate clears the value of the "subject_template" field.
func (ntuo *NotificationTemplateUpdateOne) ClearSubjectTemplate() *NotificationTemplateUpdateOne {
	ntuo.mutation.ClearSubjectTemplate()
	return ntuo
}

// SetContentTemplate sets the "content_template" field.
func (ntuo *NotificationTemplateUpdateOne) SetContentTemplate(s string) *NotificationTemplateUpdateOne {
	ntuo.mutation.SetContentTemplate(s)
	return ntuo
}

// SetNillableContentTemplate sets the "content_template" field if the given value is not nil.
func (ntuo *NotificationTemplateUpdateOne) SetNillableContentTemplate(s *string) *NotificationTemplateUpdateOne {
	if s != nil {
		ntuo.SetContentTemplate(*s)
	}
	return ntuo
}

// SetFormat sets the "format" field.
func (ntuo *NotificationTemplateUpdateOne) SetFormat(s string) *NotificationTemplateUpdateOne {
	ntuo.mutation.SetFormat(s)
	return ntuo
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (ntuo *NotificationTemplateUpdateOne) SetNillableFormat(s *string) *NotificationTemplateUpdateOne {
	if s != nil {
		ntuo.SetFormat(*s)
	}
	return ntuo
}

// SetUserID sets the "user_id" field.
func (ntuo *NotificationTemplateUpdateOne) SetUserID(i int) *NotificationTemplateUpdateOne {
	ntuo.mutation.ResetUserID()
	ntuo.mutation.SetUserID(i)
	return ntuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ntuo *NotificationTemplateUpdateOne) SetNillableUserID(i *int) *NotificationTemplateUpdateOne {
	if i != nil {
		ntuo.SetUserID(*i)
	}
	return ntuo
}

// AddUserID adds i to the "user_id" field.
func (ntuo *NotificationTemplateUpdateOne) AddUserID(i int) *NotificationTemplateUpdateOne {
	ntuo.mutation.AddUserID(i)
	return ntuo
}

// ClearUserID clears the value of the "user_id" field.
func (ntuo *NotificationTemplateUpdateOne) ClearUserID() *NotificationTemplateUpdateOne {
	ntuo.mutation.ClearUserID()
	return ntuo
}

// SetIsSystemDefault sets the "is_system_default" field.
func (ntuo *NotificationTemplateUpdateOne) SetIsSystemDefault(b bool) *NotificationTemplateUpdateOne {
	ntuo.mutation.SetIsSystemDefault(b)
	return ntuo
}

// SetNillableIsSystemDefault sets the "is_system_default" field if the given value is not nil.
func (ntuo *NotificationTemplateUpdateOne) SetNillableIsSystemDefault(b *bool) *NotificationTemplateUpdateOne {
	if b != nil {
		ntuo.SetIsSystemDefault(*b)
	}
	return ntuo
}

// SetIsActive sets the "is_active" field.
func (ntuo *NotificationTemplateUpdateOne) SetIsActive(b bool) *NotificationTemplateUpdateOne {
	ntuo.mutation.SetIsActive(b)
	return ntuo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (ntuo *NotificationTemplateUpdateOne) SetNillableIsActive(b *bool) *NotificationTemplateUpdateOne {
	if b != nil {
		ntuo.SetIsActive(*b)
	}
	return ntuo
}

// SetCreatedAt sets the "created_at" field.
func (ntuo *NotificationTemplateUpdateOne) SetCreatedAt(t time.Time) *NotificationTemplateUpdateOne {
	ntuo.mutation.SetCreatedAt(t)
	return ntuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ntuo *NotificationTemplateUpdateOne) SetNillableCreatedAt(t *time.Time) *NotificationTemplateUpdateOne {
	if t != nil {
		ntuo.SetCreatedAt(*t)
	}
	return ntuo
}

// SetUpdatedAt sets the "updated_at" field.
func (ntuo *NotificationTemplateUpdateOne) SetUpdatedAt(t time.Time) *NotificationTemplateUpdateOne {
	ntuo.mutation.SetUpdatedAt(t)
	return ntuo
}

// Mutation returns the NotificationTemplateMutation object of the builder.
func (ntuo *NotificationTemplateUpdateOne) Mutation() *NotificationTemplateMutation {
	return ntuo.mutation
}

// Where appends a list predicates to the NotificationTemplateUpdate builder.
func (ntuo *NotificationTemplateUpdateOne) Where(ps ...predicate.NotificationTemplate) *NotificationTemplateUpdateOne {
	ntuo.mutation.Where(ps...)
	return ntuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ntuo *NotificationTemplateUpdateOne) Select(field string, fields ...string) *NotificationTemplateUpdateOne {
	ntuo.fields = append([]string{field}, fields...)
	return ntuo
}

// Save executes the query and returns the updated NotificationTemplate entity.
func (ntuo *NotificationTemplateUpdateOne) Save(ctx context.Context) (*NotificationTemplate, error) {
	ntuo.defaults()
	return withHooks(ctx, ntuo.sqlSave, ntuo.mutation, ntuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ntuo *NotificationTemplateUpdateOne) SaveX(ctx context.Context) *NotificationTemplate {
	node, err := ntuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ntuo *NotificationTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := ntuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ntuo *NotificationTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := ntuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ntuo *NotificationTemplateUpdateOne) defaults() {
	if _, ok := ntuo.mutation.UpdatedAt(); !ok {
		v := notificationtemplate.UpdateDefaultUpdatedAt()
		ntuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ntuo *NotificationTemplateUpdateOne) check() error {
	if v, ok := ntuo.mutation.Name(); ok {
		if err := notificationtemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationTemplate.name": %w`, err)}
		}
	}
	if v, ok := ntuo.mutation.GetType(); ok {
		if err := notificationtemplate.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "NotificationTemplate.type": %w`, err)}
		}
	}
	if v, ok := ntuo.mutation.ContentTemplate(); ok {
		if err := notificationtemplate.ContentTemplateValidator(v); err != nil {
			return &ValidationError{Name: "content_template", err: fmt.Errorf(`ent: validator failed for field "NotificationTemplate.content_template": %w`, err)}
		}
	}
	return nil
}

func (ntuo *NotificationTemplateUpdateOne) sqlSave(ctx context.Context) (_node *NotificationTemplate, err error) {
	if err := ntuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationtemplate.Table, notificationtemplate.Columns, sqlgraph.NewFieldSpec(notificationtemplate.FieldID, field.TypeInt))
	id, ok := ntuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ntuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationtemplate.FieldID)
		for _, f := range fields {
			if !notificationtemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationtemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ntuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ntuo.mutation.Name(); ok {
		_spec.SetField(notificationtemplate.FieldName, field.TypeString, value)
	}
	if value, ok := ntuo.mutation.GetType(); ok {
		_spec.SetField(notificationtemplate.FieldType, field.TypeString, value)
	}
	if value, ok := ntuo.mutation.SubjectTemplate(); ok {
		_spec.SetField(notificationtemplate.FieldSubjectTemplate, field.TypeString, value)
	}
	if ntuo.mutation.SubjectTemplateCleared() {
		_spec.ClearField(notificationtemplate.FieldSubjectTemplate, field.TypeString)
	}
	if value, ok := ntuo.mutation.ContentTemplate(); ok {
		_spec.SetField(notificationtemplate.FieldContentTemplate, field.TypeString, value)
	}
	if value, ok := ntuo.mutation.Format(); ok {
		_spec.SetField(notificationtemplate.FieldFormat, field.TypeString, value)
	}
	if value, ok := ntuo.mutation.UserID(); ok {
		_spec.SetField(notificationtemplate.FieldUserID, field.TypeInt, value)
	}
	if value, ok := ntuo.mutation.AddedUserID(); ok {
		_spec.AddField(notificationtemplate.FieldUserID, field.TypeInt, value)
	}
	if ntuo.mutation.UserIDCleared() {
		_spec.ClearField(notificationtemplate.FieldUserID, field.TypeInt)
	}
	if value, ok := ntuo.mutation.IsSystemDefault(); ok {
		_spec.SetField(notificationtemplate.FieldIsSystemDefault, field.TypeBool, value)
	}
	if value, ok := ntuo.mutation.IsActive(); ok {
		_spec.SetField(notificationtemplate.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := ntuo.mutation.CreatedAt(); ok {
		_spec.SetField(notificationtemplate.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := ntuo.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationtemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &NotificationTemplate{config: ntuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ntuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ntuo.mutation.done = true
	return _node, nil
}
