// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/notificationconfig"
	"autoSSL/ent/predicate"
	"autoSSL/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationConfigUpdate is the builder for updating NotificationConfig entities.
type NotificationConfigUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationConfigMutation
}

// Where appends a list predicates to the NotificationConfigUpdate builder.
func (ncu *NotificationConfigUpdate) Where(ps ...predicate.NotificationConfig) *NotificationConfigUpdate {
	ncu.mutation.Where(ps...)
	return ncu
}

// SetName sets the "name" field.
func (ncu *NotificationConfigUpdate) SetName(s string) *NotificationConfigUpdate {
	ncu.mutation.SetName(s)
	return ncu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ncu *NotificationConfigUpdate) SetNillableName(s *string) *NotificationConfigUpdate {
	if s != nil {
		ncu.SetName(*s)
	}
	return ncu
}

// SetType sets the "type" field.
func (ncu *NotificationConfigUpdate) SetType(n notificationconfig.Type) *NotificationConfigUpdate {
	ncu.mutation.SetType(n)
	return ncu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (ncu *NotificationConfigUpdate) SetNillableType(n *notificationconfig.Type) *NotificationConfigUpdate {
	if n != nil {
		ncu.SetType(*n)
	}
	return ncu
}

// SetConfig sets the "config" field.
func (ncu *NotificationConfigUpdate) SetConfig(m map[string]interface{}) *NotificationConfigUpdate {
	ncu.mutation.SetConfig(m)
	return ncu
}

// SetIsActive sets the "is_active" field.
func (ncu *NotificationConfigUpdate) SetIsActive(b bool) *NotificationConfigUpdate {
	ncu.mutation.SetIsActive(b)
	return ncu
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (ncu *NotificationConfigUpdate) SetNillableIsActive(b *bool) *NotificationConfigUpdate {
	if b != nil {
		ncu.SetIsActive(*b)
	}
	return ncu
}

// SetUpdatedAt sets the "updated_at" field.
func (ncu *NotificationConfigUpdate) SetUpdatedAt(t time.Time) *NotificationConfigUpdate {
	ncu.mutation.SetUpdatedAt(t)
	return ncu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ncu *NotificationConfigUpdate) SetUserID(id int) *NotificationConfigUpdate {
	ncu.mutation.SetUserID(id)
	return ncu
}

// SetUser sets the "user" edge to the User entity.
func (ncu *NotificationConfigUpdate) SetUser(u *User) *NotificationConfigUpdate {
	return ncu.SetUserID(u.ID)
}

// Mutation returns the NotificationConfigMutation object of the builder.
func (ncu *NotificationConfigUpdate) Mutation() *NotificationConfigMutation {
	return ncu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ncu *NotificationConfigUpdate) ClearUser() *NotificationConfigUpdate {
	ncu.mutation.ClearUser()
	return ncu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ncu *NotificationConfigUpdate) Save(ctx context.Context) (int, error) {
	ncu.defaults()
	return withHooks(ctx, ncu.sqlSave, ncu.mutation, ncu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ncu *NotificationConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := ncu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ncu *NotificationConfigUpdate) Exec(ctx context.Context) error {
	_, err := ncu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncu *NotificationConfigUpdate) ExecX(ctx context.Context) {
	if err := ncu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ncu *NotificationConfigUpdate) defaults() {
	if _, ok := ncu.mutation.UpdatedAt(); !ok {
		v := notificationconfig.UpdateDefaultUpdatedAt()
		ncu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ncu *NotificationConfigUpdate) check() error {
	if v, ok := ncu.mutation.GetType(); ok {
		if err := notificationconfig.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "NotificationConfig.type": %w`, err)}
		}
	}
	if ncu.mutation.UserCleared() && len(ncu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationConfig.user"`)
	}
	return nil
}

func (ncu *NotificationConfigUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ncu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationconfig.Table, notificationconfig.Columns, sqlgraph.NewFieldSpec(notificationconfig.FieldID, field.TypeInt))
	if ps := ncu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ncu.mutation.Name(); ok {
		_spec.SetField(notificationconfig.FieldName, field.TypeString, value)
	}
	if value, ok := ncu.mutation.GetType(); ok {
		_spec.SetField(notificationconfig.FieldType, field.TypeEnum, value)
	}
	if value, ok := ncu.mutation.Config(); ok {
		_spec.SetField(notificationconfig.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := ncu.mutation.IsActive(); ok {
		_spec.SetField(notificationconfig.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := ncu.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if ncu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationconfig.UserTable,
			Columns: []string{notificationconfig.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ncu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationconfig.UserTable,
			Columns: []string{notificationconfig.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ncu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ncu.mutation.done = true
	return n, nil
}

// NotificationConfigUpdateOne is the builder for updating a single NotificationConfig entity.
type NotificationConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationConfigMutation
}

// SetName sets the "name" field.
func (ncuo *NotificationConfigUpdateOne) SetName(s string) *NotificationConfigUpdateOne {
	ncuo.mutation.SetName(s)
	return ncuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ncuo *NotificationConfigUpdateOne) SetNillableName(s *string) *NotificationConfigUpdateOne {
	if s != nil {
		ncuo.SetName(*s)
	}
	return ncuo
}

// SetType sets the "type" field.
func (ncuo *NotificationConfigUpdateOne) SetType(n notificationconfig.Type) *NotificationConfigUpdateOne {
	ncuo.mutation.SetType(n)
	return ncuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (ncuo *NotificationConfigUpdateOne) SetNillableType(n *notificationconfig.Type) *NotificationConfigUpdateOne {
	if n != nil {
		ncuo.SetType(*n)
	}
	return ncuo
}

// SetConfig sets the "config" field.
func (ncuo *NotificationConfigUpdateOne) SetConfig(m map[string]interface{}) *NotificationConfigUpdateOne {
	ncuo.mutation.SetConfig(m)
	return ncuo
}

// SetIsActive sets the "is_active" field.
func (ncuo *NotificationConfigUpdateOne) SetIsActive(b bool) *NotificationConfigUpdateOne {
	ncuo.mutation.SetIsActive(b)
	return ncuo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (ncuo *NotificationConfigUpdateOne) SetNillableIsActive(b *bool) *NotificationConfigUpdateOne {
	if b != nil {
		ncuo.SetIsActive(*b)
	}
	return ncuo
}

// SetUpdatedAt sets the "updated_at" field.
func (ncuo *NotificationConfigUpdateOne) SetUpdatedAt(t time.Time) *NotificationConfigUpdateOne {
	ncuo.mutation.SetUpdatedAt(t)
	return ncuo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ncuo *NotificationConfigUpdateOne) SetUserID(id int) *NotificationConfigUpdateOne {
	ncuo.mutation.SetUserID(id)
	return ncuo
}

// SetUser sets the "user" edge to the User entity.
func (ncuo *NotificationConfigUpdateOne) SetUser(u *User) *NotificationConfigUpdateOne {
	return ncuo.SetUserID(u.ID)
}

// Mutation returns the NotificationConfigMutation object of the builder.
func (ncuo *NotificationConfigUpdateOne) Mutation() *NotificationConfigMutation {
	return ncuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ncuo *NotificationConfigUpdateOne) ClearUser() *NotificationConfigUpdateOne {
	ncuo.mutation.ClearUser()
	return ncuo
}

// Where appends a list predicates to the NotificationConfigUpdate builder.
func (ncuo *NotificationConfigUpdateOne) Where(ps ...predicate.NotificationConfig) *NotificationConfigUpdateOne {
	ncuo.mutation.Where(ps...)
	return ncuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ncuo *NotificationConfigUpdateOne) Select(field string, fields ...string) *NotificationConfigUpdateOne {
	ncuo.fields = append([]string{field}, fields...)
	return ncuo
}

// Save executes the query and returns the updated NotificationConfig entity.
func (ncuo *NotificationConfigUpdateOne) Save(ctx context.Context) (*NotificationConfig, error) {
	ncuo.defaults()
	return withHooks(ctx, ncuo.sqlSave, ncuo.mutation, ncuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ncuo *NotificationConfigUpdateOne) SaveX(ctx context.Context) *NotificationConfig {
	node, err := ncuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ncuo *NotificationConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := ncuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncuo *NotificationConfigUpdateOne) ExecX(ctx context.Context) {
	if err := ncuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ncuo *NotificationConfigUpdateOne) defaults() {
	if _, ok := ncuo.mutation.UpdatedAt(); !ok {
		v := notificationconfig.UpdateDefaultUpdatedAt()
		ncuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ncuo *NotificationConfigUpdateOne) check() error {
	if v, ok := ncuo.mutation.GetType(); ok {
		if err := notificationconfig.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "NotificationConfig.type": %w`, err)}
		}
	}
	if ncuo.mutation.UserCleared() && len(ncuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationConfig.user"`)
	}
	return nil
}

func (ncuo *NotificationConfigUpdateOne) sqlSave(ctx context.Context) (_node *NotificationConfig, err error) {
	if err := ncuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationconfig.Table, notificationconfig.Columns, sqlgraph.NewFieldSpec(notificationconfig.FieldID, field.TypeInt))
	id, ok := ncuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ncuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationconfig.FieldID)
		for _, f := range fields {
			if !notificationconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ncuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ncuo.mutation.Name(); ok {
		_spec.SetField(notificationconfig.FieldName, field.TypeString, value)
	}
	if value, ok := ncuo.mutation.GetType(); ok {
		_spec.SetField(notificationconfig.FieldType, field.TypeEnum, value)
	}
	if value, ok := ncuo.mutation.Config(); ok {
		_spec.SetField(notificationconfig.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := ncuo.mutation.IsActive(); ok {
		_spec.SetField(notificationconfig.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := ncuo.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if ncuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationconfig.UserTable,
			Columns: []string{notificationconfig.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ncuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationconfig.UserTable,
			Columns: []string{notificationconfig.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NotificationConfig{config: ncuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ncuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ncuo.mutation.done = true
	return _node, nil
}
