// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/access"
	"autoSSL/ent/servergroup"
	"autoSSL/ent/servergroupmember"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ServerGroupMember is the model entity for the ServerGroupMember schema.
type ServerGroupMember struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 访问类型
	Type servergroupmember.Type `json:"type,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ServerGroupMemberQuery when eager-loading is set.
	Edges                            ServerGroupMemberEdges `json:"edges"`
	access_server_group_members      *int
	server_group_member_server_group *int
	selectValues                     sql.SelectValues
}

// ServerGroupMemberEdges holds the relations/edges for other nodes in the graph.
type ServerGroupMemberEdges struct {
	// 关联的服务器组
	ServerGroup *ServerGroup `json:"server_group,omitempty"`
	// 关联的访问配置
	Access *Access `json:"access,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ServerGroupOrErr returns the ServerGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServerGroupMemberEdges) ServerGroupOrErr() (*ServerGroup, error) {
	if e.ServerGroup != nil {
		return e.ServerGroup, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: servergroup.Label}
	}
	return nil, &NotLoadedError{edge: "server_group"}
}

// AccessOrErr returns the Access value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServerGroupMemberEdges) AccessOrErr() (*Access, error) {
	if e.Access != nil {
		return e.Access, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: access.Label}
	}
	return nil, &NotLoadedError{edge: "access"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ServerGroupMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case servergroupmember.FieldID:
			values[i] = new(sql.NullInt64)
		case servergroupmember.FieldType:
			values[i] = new(sql.NullString)
		case servergroupmember.FieldCreatedAt, servergroupmember.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case servergroupmember.ForeignKeys[0]: // access_server_group_members
			values[i] = new(sql.NullInt64)
		case servergroupmember.ForeignKeys[1]: // server_group_member_server_group
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ServerGroupMember fields.
func (sgm *ServerGroupMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case servergroupmember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sgm.ID = int(value.Int64)
		case servergroupmember.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				sgm.Type = servergroupmember.Type(value.String)
			}
		case servergroupmember.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sgm.CreatedAt = value.Time
			}
		case servergroupmember.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				sgm.UpdatedAt = value.Time
			}
		case servergroupmember.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field access_server_group_members", value)
			} else if value.Valid {
				sgm.access_server_group_members = new(int)
				*sgm.access_server_group_members = int(value.Int64)
			}
		case servergroupmember.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field server_group_member_server_group", value)
			} else if value.Valid {
				sgm.server_group_member_server_group = new(int)
				*sgm.server_group_member_server_group = int(value.Int64)
			}
		default:
			sgm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ServerGroupMember.
// This includes values selected through modifiers, order, etc.
func (sgm *ServerGroupMember) Value(name string) (ent.Value, error) {
	return sgm.selectValues.Get(name)
}

// QueryServerGroup queries the "server_group" edge of the ServerGroupMember entity.
func (sgm *ServerGroupMember) QueryServerGroup() *ServerGroupQuery {
	return NewServerGroupMemberClient(sgm.config).QueryServerGroup(sgm)
}

// QueryAccess queries the "access" edge of the ServerGroupMember entity.
func (sgm *ServerGroupMember) QueryAccess() *AccessQuery {
	return NewServerGroupMemberClient(sgm.config).QueryAccess(sgm)
}

// Update returns a builder for updating this ServerGroupMember.
// Note that you need to call ServerGroupMember.Unwrap() before calling this method if this ServerGroupMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (sgm *ServerGroupMember) Update() *ServerGroupMemberUpdateOne {
	return NewServerGroupMemberClient(sgm.config).UpdateOne(sgm)
}

// Unwrap unwraps the ServerGroupMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sgm *ServerGroupMember) Unwrap() *ServerGroupMember {
	_tx, ok := sgm.config.driver.(*txDriver)
	if !ok {
		panic("ent: ServerGroupMember is not a transactional entity")
	}
	sgm.config.driver = _tx.drv
	return sgm
}

// String implements the fmt.Stringer.
func (sgm *ServerGroupMember) String() string {
	var builder strings.Builder
	builder.WriteString("ServerGroupMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sgm.ID))
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", sgm.Type))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(sgm.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(sgm.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ServerGroupMembers is a parsable slice of ServerGroupMember.
type ServerGroupMembers []*ServerGroupMember
