// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/servergroup"
	"autoSSL/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ServerGroup is the model entity for the ServerGroup schema.
type ServerGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 组名称
	Name string `json:"name,omitempty"`
	// 组描述
	Description string `json:"description,omitempty"`
	// 组访问类型
	Type servergroup.Type `json:"type,omitempty"`
	// 组状态
	Status servergroup.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ServerGroupQuery when eager-loading is set.
	Edges              ServerGroupEdges `json:"edges"`
	user_server_groups *int
	selectValues       sql.SelectValues
}

// ServerGroupEdges holds the relations/edges for other nodes in the graph.
type ServerGroupEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// GroupMemberships holds the value of the group_memberships edge.
	GroupMemberships []*ServerGroupMember `json:"group_memberships,omitempty"`
	// 关联的证书部署记录
	CertificateDeployments []*CertificateDeployment `json:"certificate_deployments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServerGroupEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// GroupMembershipsOrErr returns the GroupMemberships value or an error if the edge
// was not loaded in eager-loading.
func (e ServerGroupEdges) GroupMembershipsOrErr() ([]*ServerGroupMember, error) {
	if e.loadedTypes[1] {
		return e.GroupMemberships, nil
	}
	return nil, &NotLoadedError{edge: "group_memberships"}
}

// CertificateDeploymentsOrErr returns the CertificateDeployments value or an error if the edge
// was not loaded in eager-loading.
func (e ServerGroupEdges) CertificateDeploymentsOrErr() ([]*CertificateDeployment, error) {
	if e.loadedTypes[2] {
		return e.CertificateDeployments, nil
	}
	return nil, &NotLoadedError{edge: "certificate_deployments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ServerGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case servergroup.FieldID:
			values[i] = new(sql.NullInt64)
		case servergroup.FieldName, servergroup.FieldDescription, servergroup.FieldType, servergroup.FieldStatus:
			values[i] = new(sql.NullString)
		case servergroup.FieldCreatedAt, servergroup.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case servergroup.ForeignKeys[0]: // user_server_groups
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ServerGroup fields.
func (sg *ServerGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case servergroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sg.ID = int(value.Int64)
		case servergroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				sg.Name = value.String
			}
		case servergroup.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				sg.Description = value.String
			}
		case servergroup.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				sg.Type = servergroup.Type(value.String)
			}
		case servergroup.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				sg.Status = servergroup.Status(value.String)
			}
		case servergroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sg.CreatedAt = value.Time
			}
		case servergroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				sg.UpdatedAt = value.Time
			}
		case servergroup.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_server_groups", value)
			} else if value.Valid {
				sg.user_server_groups = new(int)
				*sg.user_server_groups = int(value.Int64)
			}
		default:
			sg.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ServerGroup.
// This includes values selected through modifiers, order, etc.
func (sg *ServerGroup) Value(name string) (ent.Value, error) {
	return sg.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ServerGroup entity.
func (sg *ServerGroup) QueryUser() *UserQuery {
	return NewServerGroupClient(sg.config).QueryUser(sg)
}

// QueryGroupMemberships queries the "group_memberships" edge of the ServerGroup entity.
func (sg *ServerGroup) QueryGroupMemberships() *ServerGroupMemberQuery {
	return NewServerGroupClient(sg.config).QueryGroupMemberships(sg)
}

// QueryCertificateDeployments queries the "certificate_deployments" edge of the ServerGroup entity.
func (sg *ServerGroup) QueryCertificateDeployments() *CertificateDeploymentQuery {
	return NewServerGroupClient(sg.config).QueryCertificateDeployments(sg)
}

// Update returns a builder for updating this ServerGroup.
// Note that you need to call ServerGroup.Unwrap() before calling this method if this ServerGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (sg *ServerGroup) Update() *ServerGroupUpdateOne {
	return NewServerGroupClient(sg.config).UpdateOne(sg)
}

// Unwrap unwraps the ServerGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sg *ServerGroup) Unwrap() *ServerGroup {
	_tx, ok := sg.config.driver.(*txDriver)
	if !ok {
		panic("ent: ServerGroup is not a transactional entity")
	}
	sg.config.driver = _tx.drv
	return sg
}

// String implements the fmt.Stringer.
func (sg *ServerGroup) String() string {
	var builder strings.Builder
	builder.WriteString("ServerGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sg.ID))
	builder.WriteString("name=")
	builder.WriteString(sg.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(sg.Description)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", sg.Type))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", sg.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(sg.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(sg.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ServerGroups is a parsable slice of ServerGroup.
type ServerGroups []*ServerGroup
