// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/access"
	"autoSSL/ent/predicate"
	"autoSSL/ent/servergroup"
	"autoSSL/ent/servergroupmember"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServerGroupMemberUpdate is the builder for updating ServerGroupMember entities.
type ServerGroupMemberUpdate struct {
	config
	hooks    []Hook
	mutation *ServerGroupMemberMutation
}

// Where appends a list predicates to the ServerGroupMemberUpdate builder.
func (sgmu *ServerGroupMemberUpdate) Where(ps ...predicate.ServerGroupMember) *ServerGroupMemberUpdate {
	sgmu.mutation.Where(ps...)
	return sgmu
}

// SetType sets the "type" field.
func (sgmu *ServerGroupMemberUpdate) SetType(s servergroupmember.Type) *ServerGroupMemberUpdate {
	sgmu.mutation.SetType(s)
	return sgmu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (sgmu *ServerGroupMemberUpdate) SetNillableType(s *servergroupmember.Type) *ServerGroupMemberUpdate {
	if s != nil {
		sgmu.SetType(*s)
	}
	return sgmu
}

// SetUpdatedAt sets the "updated_at" field.
func (sgmu *ServerGroupMemberUpdate) SetUpdatedAt(t time.Time) *ServerGroupMemberUpdate {
	sgmu.mutation.SetUpdatedAt(t)
	return sgmu
}

// SetServerGroupID sets the "server_group" edge to the ServerGroup entity by ID.
func (sgmu *ServerGroupMemberUpdate) SetServerGroupID(id int) *ServerGroupMemberUpdate {
	sgmu.mutation.SetServerGroupID(id)
	return sgmu
}

// SetServerGroup sets the "server_group" edge to the ServerGroup entity.
func (sgmu *ServerGroupMemberUpdate) SetServerGroup(s *ServerGroup) *ServerGroupMemberUpdate {
	return sgmu.SetServerGroupID(s.ID)
}

// SetAccessID sets the "access" edge to the Access entity by ID.
func (sgmu *ServerGroupMemberUpdate) SetAccessID(id int) *ServerGroupMemberUpdate {
	sgmu.mutation.SetAccessID(id)
	return sgmu
}

// SetNillableAccessID sets the "access" edge to the Access entity by ID if the given value is not nil.
func (sgmu *ServerGroupMemberUpdate) SetNillableAccessID(id *int) *ServerGroupMemberUpdate {
	if id != nil {
		sgmu = sgmu.SetAccessID(*id)
	}
	return sgmu
}

// SetAccess sets the "access" edge to the Access entity.
func (sgmu *ServerGroupMemberUpdate) SetAccess(a *Access) *ServerGroupMemberUpdate {
	return sgmu.SetAccessID(a.ID)
}

// Mutation returns the ServerGroupMemberMutation object of the builder.
func (sgmu *ServerGroupMemberUpdate) Mutation() *ServerGroupMemberMutation {
	return sgmu.mutation
}

// ClearServerGroup clears the "server_group" edge to the ServerGroup entity.
func (sgmu *ServerGroupMemberUpdate) ClearServerGroup() *ServerGroupMemberUpdate {
	sgmu.mutation.ClearServerGroup()
	return sgmu
}

// ClearAccess clears the "access" edge to the Access entity.
func (sgmu *ServerGroupMemberUpdate) ClearAccess() *ServerGroupMemberUpdate {
	sgmu.mutation.ClearAccess()
	return sgmu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sgmu *ServerGroupMemberUpdate) Save(ctx context.Context) (int, error) {
	sgmu.defaults()
	return withHooks(ctx, sgmu.sqlSave, sgmu.mutation, sgmu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sgmu *ServerGroupMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := sgmu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sgmu *ServerGroupMemberUpdate) Exec(ctx context.Context) error {
	_, err := sgmu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sgmu *ServerGroupMemberUpdate) ExecX(ctx context.Context) {
	if err := sgmu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sgmu *ServerGroupMemberUpdate) defaults() {
	if _, ok := sgmu.mutation.UpdatedAt(); !ok {
		v := servergroupmember.UpdateDefaultUpdatedAt()
		sgmu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sgmu *ServerGroupMemberUpdate) check() error {
	if v, ok := sgmu.mutation.GetType(); ok {
		if err := servergroupmember.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ServerGroupMember.type": %w`, err)}
		}
	}
	if sgmu.mutation.ServerGroupCleared() && len(sgmu.mutation.ServerGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServerGroupMember.server_group"`)
	}
	return nil
}

func (sgmu *ServerGroupMemberUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := sgmu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(servergroupmember.Table, servergroupmember.Columns, sqlgraph.NewFieldSpec(servergroupmember.FieldID, field.TypeInt))
	if ps := sgmu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sgmu.mutation.GetType(); ok {
		_spec.SetField(servergroupmember.FieldType, field.TypeEnum, value)
	}
	if value, ok := sgmu.mutation.UpdatedAt(); ok {
		_spec.SetField(servergroupmember.FieldUpdatedAt, field.TypeTime, value)
	}
	if sgmu.mutation.ServerGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   servergroupmember.ServerGroupTable,
			Columns: []string{servergroupmember.ServerGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servergroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sgmu.mutation.ServerGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   servergroupmember.ServerGroupTable,
			Columns: []string{servergroupmember.ServerGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servergroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if sgmu.mutation.AccessCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   servergroupmember.AccessTable,
			Columns: []string{servergroupmember.AccessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sgmu.mutation.AccessIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   servergroupmember.AccessTable,
			Columns: []string{servergroupmember.AccessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sgmu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servergroupmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	sgmu.mutation.done = true
	return n, nil
}

// ServerGroupMemberUpdateOne is the builder for updating a single ServerGroupMember entity.
type ServerGroupMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServerGroupMemberMutation
}

// SetType sets the "type" field.
func (sgmuo *ServerGroupMemberUpdateOne) SetType(s servergroupmember.Type) *ServerGroupMemberUpdateOne {
	sgmuo.mutation.SetType(s)
	return sgmuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (sgmuo *ServerGroupMemberUpdateOne) SetNillableType(s *servergroupmember.Type) *ServerGroupMemberUpdateOne {
	if s != nil {
		sgmuo.SetType(*s)
	}
	return sgmuo
}

// SetUpdatedAt sets the "updated_at" field.
func (sgmuo *ServerGroupMemberUpdateOne) SetUpdatedAt(t time.Time) *ServerGroupMemberUpdateOne {
	sgmuo.mutation.SetUpdatedAt(t)
	return sgmuo
}

// SetServerGroupID sets the "server_group" edge to the ServerGroup entity by ID.
func (sgmuo *ServerGroupMemberUpdateOne) SetServerGroupID(id int) *ServerGroupMemberUpdateOne {
	sgmuo.mutation.SetServerGroupID(id)
	return sgmuo
}

// SetServerGroup sets the "server_group" edge to the ServerGroup entity.
func (sgmuo *ServerGroupMemberUpdateOne) SetServerGroup(s *ServerGroup) *ServerGroupMemberUpdateOne {
	return sgmuo.SetServerGroupID(s.ID)
}

// SetAccessID sets the "access" edge to the Access entity by ID.
func (sgmuo *ServerGroupMemberUpdateOne) SetAccessID(id int) *ServerGroupMemberUpdateOne {
	sgmuo.mutation.SetAccessID(id)
	return sgmuo
}

// SetNillableAccessID sets the "access" edge to the Access entity by ID if the given value is not nil.
func (sgmuo *ServerGroupMemberUpdateOne) SetNillableAccessID(id *int) *ServerGroupMemberUpdateOne {
	if id != nil {
		sgmuo = sgmuo.SetAccessID(*id)
	}
	return sgmuo
}

// SetAccess sets the "access" edge to the Access entity.
func (sgmuo *ServerGroupMemberUpdateOne) SetAccess(a *Access) *ServerGroupMemberUpdateOne {
	return sgmuo.SetAccessID(a.ID)
}

// Mutation returns the ServerGroupMemberMutation object of the builder.
func (sgmuo *ServerGroupMemberUpdateOne) Mutation() *ServerGroupMemberMutation {
	return sgmuo.mutation
}

// ClearServerGroup clears the "server_group" edge to the ServerGroup entity.
func (sgmuo *ServerGroupMemberUpdateOne) ClearServerGroup() *ServerGroupMemberUpdateOne {
	sgmuo.mutation.ClearServerGroup()
	return sgmuo
}

// ClearAccess clears the "access" edge to the Access entity.
func (sgmuo *ServerGroupMemberUpdateOne) ClearAccess() *ServerGroupMemberUpdateOne {
	sgmuo.mutation.ClearAccess()
	return sgmuo
}

// Where appends a list predicates to the ServerGroupMemberUpdate builder.
func (sgmuo *ServerGroupMemberUpdateOne) Where(ps ...predicate.ServerGroupMember) *ServerGroupMemberUpdateOne {
	sgmuo.mutation.Where(ps...)
	return sgmuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sgmuo *ServerGroupMemberUpdateOne) Select(field string, fields ...string) *ServerGroupMemberUpdateOne {
	sgmuo.fields = append([]string{field}, fields...)
	return sgmuo
}

// Save executes the query and returns the updated ServerGroupMember entity.
func (sgmuo *ServerGroupMemberUpdateOne) Save(ctx context.Context) (*ServerGroupMember, error) {
	sgmuo.defaults()
	return withHooks(ctx, sgmuo.sqlSave, sgmuo.mutation, sgmuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sgmuo *ServerGroupMemberUpdateOne) SaveX(ctx context.Context) *ServerGroupMember {
	node, err := sgmuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sgmuo *ServerGroupMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := sgmuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sgmuo *ServerGroupMemberUpdateOne) ExecX(ctx context.Context) {
	if err := sgmuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sgmuo *ServerGroupMemberUpdateOne) defaults() {
	if _, ok := sgmuo.mutation.UpdatedAt(); !ok {
		v := servergroupmember.UpdateDefaultUpdatedAt()
		sgmuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sgmuo *ServerGroupMemberUpdateOne) check() error {
	if v, ok := sgmuo.mutation.GetType(); ok {
		if err := servergroupmember.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ServerGroupMember.type": %w`, err)}
		}
	}
	if sgmuo.mutation.ServerGroupCleared() && len(sgmuo.mutation.ServerGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServerGroupMember.server_group"`)
	}
	return nil
}

func (sgmuo *ServerGroupMemberUpdateOne) sqlSave(ctx context.Context) (_node *ServerGroupMember, err error) {
	if err := sgmuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(servergroupmember.Table, servergroupmember.Columns, sqlgraph.NewFieldSpec(servergroupmember.FieldID, field.TypeInt))
	id, ok := sgmuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ServerGroupMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sgmuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, servergroupmember.FieldID)
		for _, f := range fields {
			if !servergroupmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != servergroupmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sgmuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sgmuo.mutation.GetType(); ok {
		_spec.SetField(servergroupmember.FieldType, field.TypeEnum, value)
	}
	if value, ok := sgmuo.mutation.UpdatedAt(); ok {
		_spec.SetField(servergroupmember.FieldUpdatedAt, field.TypeTime, value)
	}
	if sgmuo.mutation.ServerGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   servergroupmember.ServerGroupTable,
			Columns: []string{servergroupmember.ServerGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servergroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sgmuo.mutation.ServerGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   servergroupmember.ServerGroupTable,
			Columns: []string{servergroupmember.ServerGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servergroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if sgmuo.mutation.AccessCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   servergroupmember.AccessTable,
			Columns: []string{servergroupmember.AccessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sgmuo.mutation.AccessIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   servergroupmember.AccessTable,
			Columns: []string{servergroupmember.AccessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ServerGroupMember{config: sgmuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sgmuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servergroupmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	sgmuo.mutation.done = true
	return _node, nil
}
