// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/predicate"
	"autoSSL/ent/servergroup"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServerGroupDelete is the builder for deleting a ServerGroup entity.
type ServerGroupDelete struct {
	config
	hooks    []Hook
	mutation *ServerGroupMutation
}

// Where appends a list predicates to the ServerGroupDelete builder.
func (sgd *ServerGroupDelete) Where(ps ...predicate.ServerGroup) *ServerGroupDelete {
	sgd.mutation.Where(ps...)
	return sgd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sgd *ServerGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sgd.sqlExec, sgd.mutation, sgd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sgd *ServerGroupDelete) ExecX(ctx context.Context) int {
	n, err := sgd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sgd *ServerGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(servergroup.Table, sqlgraph.NewFieldSpec(servergroup.FieldID, field.TypeInt))
	if ps := sgd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sgd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sgd.mutation.done = true
	return affected, err
}

// ServerGroupDeleteOne is the builder for deleting a single ServerGroup entity.
type ServerGroupDeleteOne struct {
	sgd *ServerGroupDelete
}

// Where appends a list predicates to the ServerGroupDelete builder.
func (sgdo *ServerGroupDeleteOne) Where(ps ...predicate.ServerGroup) *ServerGroupDeleteOne {
	sgdo.sgd.mutation.Where(ps...)
	return sgdo
}

// Exec executes the deletion query.
func (sgdo *ServerGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := sgdo.sgd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{servergroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sgdo *ServerGroupDeleteOne) ExecX(ctx context.Context) {
	if err := sgdo.Exec(ctx); err != nil {
		panic(err)
	}
}
