// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/certificate"
	"autoSSL/ent/user"
	"autoSSL/ent/workflow"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Workflow is the model entity for the Workflow schema.
type Workflow struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 域名列表
	Domains []string `json:"domains,omitempty"`
	// 工作流状态: pending, processing, issued, deploying, completed, failed, cancelled
	Status string `json:"status,omitempty"`
	// 工作流额外配置
	ExtraConfig map[string]interface{} `json:"-"`
	// 工作流通知配置
	NotificationConfig map[string]interface{} `json:"-"`
	// 当前工作流步骤
	CurrentStep int `json:"current_step,omitempty"`
	// 总工作流步骤数
	TotalSteps int `json:"total_steps,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 完成时间
	CompletedAt time.Time `json:"completed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorkflowQuery when eager-loading is set.
	Edges                 WorkflowEdges `json:"edges"`
	certificate_workflows *int
	user_workflows        *int
	selectValues          sql.SelectValues
}

// WorkflowEdges holds the relations/edges for other nodes in the graph.
type WorkflowEdges struct {
	// Certificate holds the value of the certificate edge.
	Certificate *Certificate `json:"certificate,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Steps holds the value of the steps edge.
	Steps []*WorkflowStep `json:"steps,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// CertificateOrErr returns the Certificate value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorkflowEdges) CertificateOrErr() (*Certificate, error) {
	if e.Certificate != nil {
		return e.Certificate, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: certificate.Label}
	}
	return nil, &NotLoadedError{edge: "certificate"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorkflowEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// StepsOrErr returns the Steps value or an error if the edge
// was not loaded in eager-loading.
func (e WorkflowEdges) StepsOrErr() ([]*WorkflowStep, error) {
	if e.loadedTypes[2] {
		return e.Steps, nil
	}
	return nil, &NotLoadedError{edge: "steps"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Workflow) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workflow.FieldDomains, workflow.FieldExtraConfig, workflow.FieldNotificationConfig:
			values[i] = new([]byte)
		case workflow.FieldID, workflow.FieldCurrentStep, workflow.FieldTotalSteps:
			values[i] = new(sql.NullInt64)
		case workflow.FieldStatus:
			values[i] = new(sql.NullString)
		case workflow.FieldCreatedAt, workflow.FieldUpdatedAt, workflow.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case workflow.ForeignKeys[0]: // certificate_workflows
			values[i] = new(sql.NullInt64)
		case workflow.ForeignKeys[1]: // user_workflows
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Workflow fields.
func (w *Workflow) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workflow.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			w.ID = int(value.Int64)
		case workflow.FieldDomains:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field domains", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &w.Domains); err != nil {
					return fmt.Errorf("unmarshal field domains: %w", err)
				}
			}
		case workflow.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				w.Status = value.String
			}
		case workflow.FieldExtraConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extra_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &w.ExtraConfig); err != nil {
					return fmt.Errorf("unmarshal field extra_config: %w", err)
				}
			}
		case workflow.FieldNotificationConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field notification_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &w.NotificationConfig); err != nil {
					return fmt.Errorf("unmarshal field notification_config: %w", err)
				}
			}
		case workflow.FieldCurrentStep:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_step", values[i])
			} else if value.Valid {
				w.CurrentStep = int(value.Int64)
			}
		case workflow.FieldTotalSteps:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_steps", values[i])
			} else if value.Valid {
				w.TotalSteps = int(value.Int64)
			}
		case workflow.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				w.CreatedAt = value.Time
			}
		case workflow.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				w.UpdatedAt = value.Time
			}
		case workflow.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				w.CompletedAt = value.Time
			}
		case workflow.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field certificate_workflows", value)
			} else if value.Valid {
				w.certificate_workflows = new(int)
				*w.certificate_workflows = int(value.Int64)
			}
		case workflow.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_workflows", value)
			} else if value.Valid {
				w.user_workflows = new(int)
				*w.user_workflows = int(value.Int64)
			}
		default:
			w.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Workflow.
// This includes values selected through modifiers, order, etc.
func (w *Workflow) Value(name string) (ent.Value, error) {
	return w.selectValues.Get(name)
}

// QueryCertificate queries the "certificate" edge of the Workflow entity.
func (w *Workflow) QueryCertificate() *CertificateQuery {
	return NewWorkflowClient(w.config).QueryCertificate(w)
}

// QueryUser queries the "user" edge of the Workflow entity.
func (w *Workflow) QueryUser() *UserQuery {
	return NewWorkflowClient(w.config).QueryUser(w)
}

// QuerySteps queries the "steps" edge of the Workflow entity.
func (w *Workflow) QuerySteps() *WorkflowStepQuery {
	return NewWorkflowClient(w.config).QuerySteps(w)
}

// Update returns a builder for updating this Workflow.
// Note that you need to call Workflow.Unwrap() before calling this method if this Workflow
// was returned from a transaction, and the transaction was committed or rolled back.
func (w *Workflow) Update() *WorkflowUpdateOne {
	return NewWorkflowClient(w.config).UpdateOne(w)
}

// Unwrap unwraps the Workflow entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (w *Workflow) Unwrap() *Workflow {
	_tx, ok := w.config.driver.(*txDriver)
	if !ok {
		panic("ent: Workflow is not a transactional entity")
	}
	w.config.driver = _tx.drv
	return w
}

// String implements the fmt.Stringer.
func (w *Workflow) String() string {
	var builder strings.Builder
	builder.WriteString("Workflow(")
	builder.WriteString(fmt.Sprintf("id=%v, ", w.ID))
	builder.WriteString("domains=")
	builder.WriteString(fmt.Sprintf("%v", w.Domains))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(w.Status)
	builder.WriteString(", ")
	builder.WriteString("extra_config=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("notification_config=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("current_step=")
	builder.WriteString(fmt.Sprintf("%v", w.CurrentStep))
	builder.WriteString(", ")
	builder.WriteString("total_steps=")
	builder.WriteString(fmt.Sprintf("%v", w.TotalSteps))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(w.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(w.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("completed_at=")
	builder.WriteString(w.CompletedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Workflows is a parsable slice of Workflow.
type Workflows []*Workflow
