// Code generated by ent, DO NOT EDIT.

package ent

import (
	"autoSSL/ent/certificate"
	"autoSSL/ent/predicate"
	"autoSSL/ent/user"
	"autoSSL/ent/workflow"
	"autoSSL/ent/workflowstep"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkflowStepQuery is the builder for querying WorkflowStep entities.
type WorkflowStepQuery struct {
	config
	ctx             *QueryContext
	order           []workflowstep.OrderOption
	inters          []Interceptor
	predicates      []predicate.WorkflowStep
	withCertificate *CertificateQuery
	withUser        *UserQuery
	withWorkflow    *WorkflowQuery
	withFKs         bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WorkflowStepQuery builder.
func (wsq *WorkflowStepQuery) Where(ps ...predicate.WorkflowStep) *WorkflowStepQuery {
	wsq.predicates = append(wsq.predicates, ps...)
	return wsq
}

// Limit the number of records to be returned by this query.
func (wsq *WorkflowStepQuery) Limit(limit int) *WorkflowStepQuery {
	wsq.ctx.Limit = &limit
	return wsq
}

// Offset to start from.
func (wsq *WorkflowStepQuery) Offset(offset int) *WorkflowStepQuery {
	wsq.ctx.Offset = &offset
	return wsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wsq *WorkflowStepQuery) Unique(unique bool) *WorkflowStepQuery {
	wsq.ctx.Unique = &unique
	return wsq
}

// Order specifies how the records should be ordered.
func (wsq *WorkflowStepQuery) Order(o ...workflowstep.OrderOption) *WorkflowStepQuery {
	wsq.order = append(wsq.order, o...)
	return wsq
}

// QueryCertificate chains the current query on the "certificate" edge.
func (wsq *WorkflowStepQuery) QueryCertificate() *CertificateQuery {
	query := (&CertificateClient{config: wsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workflowstep.Table, workflowstep.FieldID, selector),
			sqlgraph.To(certificate.Table, certificate.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, workflowstep.CertificateTable, workflowstep.CertificateColumn),
		)
		fromU = sqlgraph.SetNeighbors(wsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (wsq *WorkflowStepQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: wsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workflowstep.Table, workflowstep.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, workflowstep.UserTable, workflowstep.UserPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(wsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkflow chains the current query on the "workflow" edge.
func (wsq *WorkflowStepQuery) QueryWorkflow() *WorkflowQuery {
	query := (&WorkflowClient{config: wsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workflowstep.Table, workflowstep.FieldID, selector),
			sqlgraph.To(workflow.Table, workflow.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, workflowstep.WorkflowTable, workflowstep.WorkflowColumn),
		)
		fromU = sqlgraph.SetNeighbors(wsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WorkflowStep entity from the query.
// Returns a *NotFoundError when no WorkflowStep was found.
func (wsq *WorkflowStepQuery) First(ctx context.Context) (*WorkflowStep, error) {
	nodes, err := wsq.Limit(1).All(setContextOp(ctx, wsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{workflowstep.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wsq *WorkflowStepQuery) FirstX(ctx context.Context) *WorkflowStep {
	node, err := wsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WorkflowStep ID from the query.
// Returns a *NotFoundError when no WorkflowStep ID was found.
func (wsq *WorkflowStepQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wsq.Limit(1).IDs(setContextOp(ctx, wsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{workflowstep.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wsq *WorkflowStepQuery) FirstIDX(ctx context.Context) int {
	id, err := wsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WorkflowStep entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WorkflowStep entity is found.
// Returns a *NotFoundError when no WorkflowStep entities are found.
func (wsq *WorkflowStepQuery) Only(ctx context.Context) (*WorkflowStep, error) {
	nodes, err := wsq.Limit(2).All(setContextOp(ctx, wsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{workflowstep.Label}
	default:
		return nil, &NotSingularError{workflowstep.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wsq *WorkflowStepQuery) OnlyX(ctx context.Context) *WorkflowStep {
	node, err := wsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WorkflowStep ID in the query.
// Returns a *NotSingularError when more than one WorkflowStep ID is found.
// Returns a *NotFoundError when no entities are found.
func (wsq *WorkflowStepQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wsq.Limit(2).IDs(setContextOp(ctx, wsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{workflowstep.Label}
	default:
		err = &NotSingularError{workflowstep.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wsq *WorkflowStepQuery) OnlyIDX(ctx context.Context) int {
	id, err := wsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WorkflowSteps.
func (wsq *WorkflowStepQuery) All(ctx context.Context) ([]*WorkflowStep, error) {
	ctx = setContextOp(ctx, wsq.ctx, ent.OpQueryAll)
	if err := wsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WorkflowStep, *WorkflowStepQuery]()
	return withInterceptors[[]*WorkflowStep](ctx, wsq, qr, wsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wsq *WorkflowStepQuery) AllX(ctx context.Context) []*WorkflowStep {
	nodes, err := wsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WorkflowStep IDs.
func (wsq *WorkflowStepQuery) IDs(ctx context.Context) (ids []int, err error) {
	if wsq.ctx.Unique == nil && wsq.path != nil {
		wsq.Unique(true)
	}
	ctx = setContextOp(ctx, wsq.ctx, ent.OpQueryIDs)
	if err = wsq.Select(workflowstep.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wsq *WorkflowStepQuery) IDsX(ctx context.Context) []int {
	ids, err := wsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wsq *WorkflowStepQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wsq.ctx, ent.OpQueryCount)
	if err := wsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wsq, querierCount[*WorkflowStepQuery](), wsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wsq *WorkflowStepQuery) CountX(ctx context.Context) int {
	count, err := wsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wsq *WorkflowStepQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wsq.ctx, ent.OpQueryExist)
	switch _, err := wsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wsq *WorkflowStepQuery) ExistX(ctx context.Context) bool {
	exist, err := wsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WorkflowStepQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wsq *WorkflowStepQuery) Clone() *WorkflowStepQuery {
	if wsq == nil {
		return nil
	}
	return &WorkflowStepQuery{
		config:          wsq.config,
		ctx:             wsq.ctx.Clone(),
		order:           append([]workflowstep.OrderOption{}, wsq.order...),
		inters:          append([]Interceptor{}, wsq.inters...),
		predicates:      append([]predicate.WorkflowStep{}, wsq.predicates...),
		withCertificate: wsq.withCertificate.Clone(),
		withUser:        wsq.withUser.Clone(),
		withWorkflow:    wsq.withWorkflow.Clone(),
		// clone intermediate query.
		sql:  wsq.sql.Clone(),
		path: wsq.path,
	}
}

// WithCertificate tells the query-builder to eager-load the nodes that are connected to
// the "certificate" edge. The optional arguments are used to configure the query builder of the edge.
func (wsq *WorkflowStepQuery) WithCertificate(opts ...func(*CertificateQuery)) *WorkflowStepQuery {
	query := (&CertificateClient{config: wsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wsq.withCertificate = query
	return wsq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (wsq *WorkflowStepQuery) WithUser(opts ...func(*UserQuery)) *WorkflowStepQuery {
	query := (&UserClient{config: wsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wsq.withUser = query
	return wsq
}

// WithWorkflow tells the query-builder to eager-load the nodes that are connected to
// the "workflow" edge. The optional arguments are used to configure the query builder of the edge.
func (wsq *WorkflowStepQuery) WithWorkflow(opts ...func(*WorkflowQuery)) *WorkflowStepQuery {
	query := (&WorkflowClient{config: wsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wsq.withWorkflow = query
	return wsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WorkflowStep.Query().
//		GroupBy(workflowstep.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wsq *WorkflowStepQuery) GroupBy(field string, fields ...string) *WorkflowStepGroupBy {
	wsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WorkflowStepGroupBy{build: wsq}
	grbuild.flds = &wsq.ctx.Fields
	grbuild.label = workflowstep.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.WorkflowStep.Query().
//		Select(workflowstep.FieldName).
//		Scan(ctx, &v)
func (wsq *WorkflowStepQuery) Select(fields ...string) *WorkflowStepSelect {
	wsq.ctx.Fields = append(wsq.ctx.Fields, fields...)
	sbuild := &WorkflowStepSelect{WorkflowStepQuery: wsq}
	sbuild.label = workflowstep.Label
	sbuild.flds, sbuild.scan = &wsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WorkflowStepSelect configured with the given aggregations.
func (wsq *WorkflowStepQuery) Aggregate(fns ...AggregateFunc) *WorkflowStepSelect {
	return wsq.Select().Aggregate(fns...)
}

func (wsq *WorkflowStepQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wsq); err != nil {
				return err
			}
		}
	}
	for _, f := range wsq.ctx.Fields {
		if !workflowstep.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wsq.path != nil {
		prev, err := wsq.path(ctx)
		if err != nil {
			return err
		}
		wsq.sql = prev
	}
	return nil
}

func (wsq *WorkflowStepQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WorkflowStep, error) {
	var (
		nodes       = []*WorkflowStep{}
		withFKs     = wsq.withFKs
		_spec       = wsq.querySpec()
		loadedTypes = [3]bool{
			wsq.withCertificate != nil,
			wsq.withUser != nil,
			wsq.withWorkflow != nil,
		}
	)
	if wsq.withCertificate != nil || wsq.withWorkflow != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, workflowstep.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WorkflowStep).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WorkflowStep{config: wsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := wsq.withCertificate; query != nil {
		if err := wsq.loadCertificate(ctx, query, nodes, nil,
			func(n *WorkflowStep, e *Certificate) { n.Edges.Certificate = e }); err != nil {
			return nil, err
		}
	}
	if query := wsq.withUser; query != nil {
		if err := wsq.loadUser(ctx, query, nodes,
			func(n *WorkflowStep) { n.Edges.User = []*User{} },
			func(n *WorkflowStep, e *User) { n.Edges.User = append(n.Edges.User, e) }); err != nil {
			return nil, err
		}
	}
	if query := wsq.withWorkflow; query != nil {
		if err := wsq.loadWorkflow(ctx, query, nodes, nil,
			func(n *WorkflowStep, e *Workflow) { n.Edges.Workflow = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (wsq *WorkflowStepQuery) loadCertificate(ctx context.Context, query *CertificateQuery, nodes []*WorkflowStep, init func(*WorkflowStep), assign func(*WorkflowStep, *Certificate)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*WorkflowStep)
	for i := range nodes {
		if nodes[i].certificate_workflow_steps == nil {
			continue
		}
		fk := *nodes[i].certificate_workflow_steps
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(certificate.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "certificate_workflow_steps" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (wsq *WorkflowStepQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*WorkflowStep, init func(*WorkflowStep), assign func(*WorkflowStep, *User)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*WorkflowStep)
	nids := make(map[int]map[*WorkflowStep]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(workflowstep.UserTable)
		s.Join(joinT).On(s.C(user.FieldID), joinT.C(workflowstep.UserPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(workflowstep.UserPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(workflowstep.UserPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*WorkflowStep]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*User](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "user" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (wsq *WorkflowStepQuery) loadWorkflow(ctx context.Context, query *WorkflowQuery, nodes []*WorkflowStep, init func(*WorkflowStep), assign func(*WorkflowStep, *Workflow)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*WorkflowStep)
	for i := range nodes {
		if nodes[i].workflow_steps == nil {
			continue
		}
		fk := *nodes[i].workflow_steps
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(workflow.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "workflow_steps" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (wsq *WorkflowStepQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wsq.querySpec()
	_spec.Node.Columns = wsq.ctx.Fields
	if len(wsq.ctx.Fields) > 0 {
		_spec.Unique = wsq.ctx.Unique != nil && *wsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wsq.driver, _spec)
}

func (wsq *WorkflowStepQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(workflowstep.Table, workflowstep.Columns, sqlgraph.NewFieldSpec(workflowstep.FieldID, field.TypeInt))
	_spec.From = wsq.sql
	if unique := wsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wsq.path != nil {
		_spec.Unique = true
	}
	if fields := wsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowstep.FieldID)
		for i := range fields {
			if fields[i] != workflowstep.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wsq *WorkflowStepQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wsq.driver.Dialect())
	t1 := builder.Table(workflowstep.Table)
	columns := wsq.ctx.Fields
	if len(columns) == 0 {
		columns = workflowstep.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wsq.sql != nil {
		selector = wsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wsq.ctx.Unique != nil && *wsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wsq.predicates {
		p(selector)
	}
	for _, p := range wsq.order {
		p(selector)
	}
	if offset := wsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WorkflowStepGroupBy is the group-by builder for WorkflowStep entities.
type WorkflowStepGroupBy struct {
	selector
	build *WorkflowStepQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wsgb *WorkflowStepGroupBy) Aggregate(fns ...AggregateFunc) *WorkflowStepGroupBy {
	wsgb.fns = append(wsgb.fns, fns...)
	return wsgb
}

// Scan applies the selector query and scans the result into the given value.
func (wsgb *WorkflowStepGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wsgb.build.ctx, ent.OpQueryGroupBy)
	if err := wsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkflowStepQuery, *WorkflowStepGroupBy](ctx, wsgb.build, wsgb, wsgb.build.inters, v)
}

func (wsgb *WorkflowStepGroupBy) sqlScan(ctx context.Context, root *WorkflowStepQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wsgb.fns))
	for _, fn := range wsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wsgb.flds)+len(wsgb.fns))
		for _, f := range *wsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WorkflowStepSelect is the builder for selecting fields of WorkflowStep entities.
type WorkflowStepSelect struct {
	*WorkflowStepQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wss *WorkflowStepSelect) Aggregate(fns ...AggregateFunc) *WorkflowStepSelect {
	wss.fns = append(wss.fns, fns...)
	return wss
}

// Scan applies the selector query and scans the result into the given value.
func (wss *WorkflowStepSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wss.ctx, ent.OpQuerySelect)
	if err := wss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkflowStepQuery, *WorkflowStepSelect](ctx, wss.WorkflowStepQuery, wss, wss.inters, v)
}

func (wss *WorkflowStepSelect) sqlScan(ctx context.Context, root *WorkflowStepQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wss.fns))
	for _, fn := range wss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
