// Code generated by ent, DO NOT EDIT.

package dnsprovider

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the dnsprovider type in the database.
	Label = "dns_provider"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProviderType holds the string denoting the provider_type field in the database.
	FieldProviderType = "provider_type"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeCertificates holds the string denoting the certificates edge name in mutations.
	EdgeCertificates = "certificates"
	// Table holds the table name of the dnsprovider in the database.
	Table = "dns_providers"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "dns_providers"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_dns_providers"
	// CertificatesTable is the table that holds the certificates relation/edge.
	CertificatesTable = "certificates"
	// CertificatesInverseTable is the table name for the Certificate entity.
	// It exists in this package in order to avoid circular dependency with the "certificate" package.
	CertificatesInverseTable = "certificates"
	// CertificatesColumn is the table column denoting the certificates relation/edge.
	CertificatesColumn = "dns_provider_certificates"
)

// Columns holds all SQL columns for dnsprovider fields.
var Columns = []string{
	FieldID,
	FieldProviderType,
	FieldConfig,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "dns_providers"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_dns_providers",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// ProviderType defines the type for the "provider_type" enum field.
type ProviderType string

// ProviderType values.
const (
	ProviderTypeCloudflare   ProviderType = "cloudflare"
	ProviderTypeAlidns       ProviderType = "alidns"
	ProviderTypeTencentcloud ProviderType = "tencentcloud"
)

func (pt ProviderType) String() string {
	return string(pt)
}

// ProviderTypeValidator is a validator for the "provider_type" field enum values. It is called by the builders before save.
func ProviderTypeValidator(pt ProviderType) error {
	switch pt {
	case ProviderTypeCloudflare, ProviderTypeAlidns, ProviderTypeTencentcloud:
		return nil
	default:
		return fmt.Errorf("dnsprovider: invalid enum value for provider_type field: %q", pt)
	}
}

// OrderOption defines the ordering options for the DNSProvider queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProviderType orders the results by the provider_type field.
func ByProviderType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderType, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByCertificatesCount orders the results by certificates count.
func ByCertificatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCertificatesStep(), opts...)
	}
}

// ByCertificates orders the results by certificates terms.
func ByCertificates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCertificatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newCertificatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CertificatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CertificatesTable, CertificatesColumn),
	)
}
