// Code generated by ent, DO NOT EDIT.

package certificatedeployment

import (
	"autoSSL/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldLTE(FieldID, id))
}

// DeployedAt applies equality check predicate on the "deployed_at" field. It's identical to DeployedAtEQ.
func DeployedAt(v time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldEQ(FieldDeployedAt, v))
}

// Log applies equality check predicate on the "log" field. It's identical to LogEQ.
func Log(v string) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldEQ(FieldLog, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldEQ(FieldCreatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldNotIn(FieldStatus, vs...))
}

// DeployedAtEQ applies the EQ predicate on the "deployed_at" field.
func DeployedAtEQ(v time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldEQ(FieldDeployedAt, v))
}

// DeployedAtNEQ applies the NEQ predicate on the "deployed_at" field.
func DeployedAtNEQ(v time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldNEQ(FieldDeployedAt, v))
}

// DeployedAtIn applies the In predicate on the "deployed_at" field.
func DeployedAtIn(vs ...time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldIn(FieldDeployedAt, vs...))
}

// DeployedAtNotIn applies the NotIn predicate on the "deployed_at" field.
func DeployedAtNotIn(vs ...time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldNotIn(FieldDeployedAt, vs...))
}

// DeployedAtGT applies the GT predicate on the "deployed_at" field.
func DeployedAtGT(v time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldGT(FieldDeployedAt, v))
}

// DeployedAtGTE applies the GTE predicate on the "deployed_at" field.
func DeployedAtGTE(v time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldGTE(FieldDeployedAt, v))
}

// DeployedAtLT applies the LT predicate on the "deployed_at" field.
func DeployedAtLT(v time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldLT(FieldDeployedAt, v))
}

// DeployedAtLTE applies the LTE predicate on the "deployed_at" field.
func DeployedAtLTE(v time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldLTE(FieldDeployedAt, v))
}

// DeployedAtIsNil applies the IsNil predicate on the "deployed_at" field.
func DeployedAtIsNil() predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldIsNull(FieldDeployedAt))
}

// DeployedAtNotNil applies the NotNil predicate on the "deployed_at" field.
func DeployedAtNotNil() predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldNotNull(FieldDeployedAt))
}

// LogEQ applies the EQ predicate on the "log" field.
func LogEQ(v string) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldEQ(FieldLog, v))
}

// LogNEQ applies the NEQ predicate on the "log" field.
func LogNEQ(v string) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldNEQ(FieldLog, v))
}

// LogIn applies the In predicate on the "log" field.
func LogIn(vs ...string) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldIn(FieldLog, vs...))
}

// LogNotIn applies the NotIn predicate on the "log" field.
func LogNotIn(vs ...string) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldNotIn(FieldLog, vs...))
}

// LogGT applies the GT predicate on the "log" field.
func LogGT(v string) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldGT(FieldLog, v))
}

// LogGTE applies the GTE predicate on the "log" field.
func LogGTE(v string) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldGTE(FieldLog, v))
}

// LogLT applies the LT predicate on the "log" field.
func LogLT(v string) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldLT(FieldLog, v))
}

// LogLTE applies the LTE predicate on the "log" field.
func LogLTE(v string) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldLTE(FieldLog, v))
}

// LogContains applies the Contains predicate on the "log" field.
func LogContains(v string) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldContains(FieldLog, v))
}

// LogHasPrefix applies the HasPrefix predicate on the "log" field.
func LogHasPrefix(v string) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldHasPrefix(FieldLog, v))
}

// LogHasSuffix applies the HasSuffix predicate on the "log" field.
func LogHasSuffix(v string) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldHasSuffix(FieldLog, v))
}

// LogIsNil applies the IsNil predicate on the "log" field.
func LogIsNil() predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldIsNull(FieldLog))
}

// LogNotNil applies the NotNil predicate on the "log" field.
func LogNotNil() predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldNotNull(FieldLog))
}

// LogEqualFold applies the EqualFold predicate on the "log" field.
func LogEqualFold(v string) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldEqualFold(FieldLog, v))
}

// LogContainsFold applies the ContainsFold predicate on the "log" field.
func LogContainsFold(v string) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldContainsFold(FieldLog, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.FieldLTE(FieldCreatedAt, v))
}

// HasCertificate applies the HasEdge predicate on the "certificate" edge.
func HasCertificate() predicate.CertificateDeployment {
	return predicate.CertificateDeployment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CertificateTable, CertificateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCertificateWith applies the HasEdge predicate on the "certificate" edge with a given conditions (other predicates).
func HasCertificateWith(preds ...predicate.Certificate) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(func(s *sql.Selector) {
		step := newCertificateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccess applies the HasEdge predicate on the "access" edge.
func HasAccess() predicate.CertificateDeployment {
	return predicate.CertificateDeployment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, AccessTable, AccessPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccessWith applies the HasEdge predicate on the "access" edge with a given conditions (other predicates).
func HasAccessWith(preds ...predicate.Access) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(func(s *sql.Selector) {
		step := newAccessStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasServerGroup applies the HasEdge predicate on the "server_group" edge.
func HasServerGroup() predicate.CertificateDeployment {
	return predicate.CertificateDeployment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ServerGroupTable, ServerGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServerGroupWith applies the HasEdge predicate on the "server_group" edge with a given conditions (other predicates).
func HasServerGroupWith(preds ...predicate.ServerGroup) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(func(s *sql.Selector) {
		step := newServerGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CertificateDeployment) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CertificateDeployment) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CertificateDeployment) predicate.CertificateDeployment {
	return predicate.CertificateDeployment(sql.NotPredicates(p))
}
